/**
 * Human-friendly reference helpers. Booking/quotation/work-order refs are
 * generated by column defaults (`app.next_ref`). Receipt numbers come from
 * `receipt_ref_seq` via the service-role RPC `public.next_receipt_no()`
 * (migration 0002); if the RPC is unavailable we emulate `nextval` with
 * max+1 and rely on the unique constraint (retry on 23505).
 */
import { randomInt } from 'node:crypto';
import { logger } from '../middleware/correlation.js';
import type { Db } from './supabase.js';

export const RECEIPT_SEQ_START = 70000;
const RECEIPT_RE = /^RCP-(\d+)$/;

/** Allocates the next receipt number from the DB sequence, falling back to max+1. */
export async function nextReceiptNo(db: Db): Promise<string> {
  try {
    const res = await db.rpc('next_receipt_no');
    if (!res.error && typeof res.data === 'string' && RECEIPT_RE.test(res.data)) return res.data;
    logger.warn({ err: res.error ?? null, data: res.data ?? null }, 'next_receipt_no RPC unavailable; falling back to max+1');
  } catch (err) {
    logger.warn({ err }, 'next_receipt_no RPC threw; falling back to max+1');
  }
  return nextReceiptNoFallback(db);
}

/** Legacy allocator: highest existing RCP-<n> + 1 (unique constraint guards races). */
export async function nextReceiptNoFallback(db: Db): Promise<string> {
  const res = await db.from('payments').select('receipt_no').not('receipt_no', 'is', null).order('receipt_no', { ascending: false }).limit(50);
  let max = RECEIPT_SEQ_START;
  for (const row of (res.data ?? []) as Array<{ receipt_no: string | null }>) {
    const n = parseReceiptNo(row.receipt_no);
    if (n !== null && n >= max) max = n + 1;
  }
  return `RCP-${max}`;
}

export function parseReceiptNo(receipt: string | null | undefined): number | null {
  if (!receipt) return null;
  const m = RECEIPT_RE.exec(receipt);
  return m ? Number(m[1]) : null;
}

/** Reward codes: RW-<4 digits>. */
export function newRewardCode(): string {
  return `RW-${randomInt(1000, 10000)}`;
}

export function encodeCursor(offset: number): string {
  return Buffer.from(JSON.stringify({ o: offset }), 'utf8').toString('base64url');
}

export function decodeCursor(cursor: string | undefined | null): number {
  if (!cursor) return 0;
  try {
    const parsed = JSON.parse(Buffer.from(cursor, 'base64url').toString('utf8')) as { o?: unknown };
    const o = Number(parsed.o);
    return Number.isFinite(o) && o >= 0 ? Math.floor(o) : 0;
  } catch {
    return 0;
  }
}

/** Paginate an already-fetched (limit+1) page. */
export function pageResult<T>(rows: T[], limit: number, offset: number): { data: T[]; next_cursor: string | null } {
  const hasMore = rows.length > limit;
  const data = hasMore ? rows.slice(0, limit) : rows;
  return { data, next_cursor: hasMore ? encodeCursor(offset + limit) : null };
}

export function parseSort(sort: string | undefined, allowed: string[], fallback: { column: string; ascending: boolean }) {
  if (!sort) return fallback;
  const [col, dir] = sort.split(':');
  if (!allowed.includes(col)) return fallback;
  return { column: col, ascending: dir !== 'desc' };
}
