/* Generates openapi.yaml (API-012). Run: node scripts/gen-openapi.cjs */
const fs = require('node:fs');
const yaml = require('js-yaml');

const ERR = { $ref: '#/components/schemas/ErrorEnvelope' };
const errResp = (desc) => ({ description: desc, content: { 'application/json': { schema: ERR } } });
const common = {
  400: { $ref: '#/components/responses/ValidationError' },
  401: { $ref: '#/components/responses/Unauthenticated' },
  403: { $ref: '#/components/responses/Forbidden' },
  404: { $ref: '#/components/responses/NotFound' },
  409: { $ref: '#/components/responses/Conflict' },
  429: { $ref: '#/components/responses/RateLimited' },
  500: { $ref: '#/components/responses/Internal' },
};
const json = (schema, desc = 'OK') => ({ description: desc, content: { 'application/json': { schema } } });
const obj = (props, required) => ({ type: 'object', properties: props, ...(required ? { required } : {}) });
const str = (extra = {}) => ({ type: 'string', ...extra });
const int = (extra = {}) => ({ type: 'integer', ...extra });
const num = (extra = {}) => ({ type: 'number', ...extra });
const bool = () => ({ type: 'boolean' });
const uuid = () => str({ format: 'uuid' });
const dt = () => str({ format: 'date-time' });
const date = () => str({ format: 'date' });
const arr = (items) => ({ type: 'array', items });
const ref = (n) => ({ $ref: `#/components/schemas/${n}` });
const nullable = (s) => (s.$ref ? { type: 'object', allOf: [s], nullable: true } : { ...s, nullable: true });
const enumOf = (v) => str({ enum: v });
const q = (name, schema, required = false, description) => ({ name, in: 'query', required, schema, ...(description ? { description } : {}) });
const p = (name, schema = uuid()) => ({ name, in: 'path', required: true, schema });
const body = (schema, required = true) => ({ required, content: { 'application/json': { schema } } });
const dateOrDt = { type: 'string', description: 'YYYY-MM-DD or RFC 3339 date-time', example: '2026-09-01' };
const paged = (item) => obj({ data: arr(item), next_cursor: nullable(str()) }, ['data', 'next_cursor']);
const pageParams = [q('limit', int({ minimum: 1, maximum: 100, default: 25 })), q('cursor', str()), q('sort', str({ example: 'slot_start:desc' }))];

const roles = ['customer', 'technician', 'supervisor', 'manager', 'admin', 'finance'];
const bookingStatus = ['draft', 'pending', 'confirmed', 'in_service', 'completed', 'cancelled'];
const quotationStatus = ['requested', 'assessing', 'quoted', 'accepted', 'declined', 'expired', 'converted'];
const workStatus = ['queued', 'assigned', 'in_progress', 'blocked', 'completed', 'verified', 'cancelled'];
const paymentStatus = ['initiated', 'pending', 'successful', 'failed', 'cancelled', 'refunded'];
const tiers = ['silver', 'gold', 'platinum'];

const schemas = {
  ErrorEnvelope: obj({ error: obj({ code: enumOf(['unauthenticated', 'forbidden', 'not_found', 'validation_error', 'conflict', 'invalid_transition', 'invalid_otp', 'rate_limited', 'internal']), message: str(), details: { type: 'array', items: {} }, correlation_id: str() }, ['code', 'message', 'correlation_id']) }, ['error']),
  Profile: obj({ id: str({ description: 'Firebase UID' }), role: enumOf(roles), full_name: str(), email: nullable(str({ format: 'email' })), phone: nullable(str()), avatar_url: nullable(str()), is_active: bool(), marketing_opt_in: bool(), whatsapp_opt_in: bool(), push_opt_in: bool(), locale: str(), reduced_motion: bool(), haptics: bool(), last_seen_at: nullable(dt()), created_at: dt(), updated_at: dt() }, ['id', 'role', 'full_name']),
  Outlet: obj({ id: uuid(), code: str(), name: str(), address_line: nullable(str()), city: nullable(str()), province: nullable(str()), country: str(), latitude: nullable(num()), longitude: nullable(num()), phone: nullable(str()), email: nullable(str()), timezone: str(), opening_hours: { type: 'object', additionalProperties: true }, slot_minutes: int(), bay_count: int(), rating: nullable(num()), is_active: bool(), distance_km: num({ description: 'Present when ?lat&lng supplied' }) }),
  Service: obj({ id: uuid(), code: str(), name: str(), description: nullable(str()), category: enumOf(['car_wash', 'auto_body']), duration_minutes: int(), base_price_cents: int(), is_quote_based: bool(), points_per_rand: num(), icon: nullable(str()), checklist_template_id: nullable(uuid()), is_active: bool(), sort_order: int() }),
  OutletService: { allOf: [ref('Service'), obj({ price_cents: int({ description: 'Effective price (outlet override or base)' }), discount_cents: int(), total_cents: int(), discount_label: nullable(str()), points_estimate: int() })] },
  Slot: obj({ slot_start: dt(), slot_end: dt(), capacity: int(), booked: int(), available: bool() }),
  Vehicle: obj({ id: uuid(), customer_id: str(), registration_no: str(), vin: nullable(str()), engine_no: nullable(str()), make: nullable(str()), model: nullable(str()), colour: nullable(str()), year: nullable(int()), licence_no: nullable(str()), disc_expiry: nullable(date()), source: enumOf(['manual', 'scan']), disc_verified: bool(), disc_hash: nullable(str()), is_active: bool(), created_at: dt(), updated_at: dt() }),
  VehicleCreate: obj({ registration_no: str(), vin: nullable(str({ minLength: 17, maxLength: 17 })), make: nullable(str()), model: nullable(str()), colour: nullable(str()), year: nullable(int()), licence_no: nullable(str()), disc_expiry: nullable(date()), engine_no: nullable(str()), source: enumOf(['manual', 'scan']), disc_hash: nullable(str({ description: 'sha256 of the raw disc payload (raw is never stored)' })), force: bool(), client_op_id: str() }, ['registration_no']),
  ParsedDisc: obj({ registration_no: str(), licence_no: nullable(str()), vehicle_register_no: nullable(str()), description: nullable(str()), make: nullable(str()), model: nullable(str()), colour: nullable(str()), vin: nullable(str()), engine_no: nullable(str()), disc_expiry: nullable(date()), disc_hash: str(), warnings: arr(str()), source: str({ enum: ['scan'] }) }),
  WorkOrderSummary: obj({ id: uuid(), ref: str(), status: enumOf(workStatus), stage: int(), stage_count: int(), progress_pct: int(), eta_at: nullable(dt()), assignee_name: nullable(str()), bay: nullable(str()), blocked_reason: nullable(str()), verified_at: nullable(dt()), pickup_otp_verified_at: nullable(dt()), collected_at: nullable(dt()), pickup_otp: str({ description: 'Only on GET /bookings/:id for the owning customer while the booking is completed and the vehicle uncollected; omitted otherwise', example: '48213' }), pickup_otp_issued_at: dt(), updated_at: dt() }),
  Booking: obj({ id: uuid(), ref: str({ example: 'SPK-2026-0091' }), customer_id: str(), vehicle_id: uuid(), outlet_id: uuid(), service_id: uuid(), quotation_id: nullable(uuid()), slot_start: dt(), slot_end: dt(), status: enumOf(bookingStatus), price_cents: int(), discount_cents: int(), total_cents: int(), discount_label: nullable(str({ example: 'Gold −10%' })), points_pending: int(), notes: nullable(str()), cancel_reason: nullable(str()), client_op_id: nullable(str()), created_at: dt(), updated_at: dt(), outlet: obj({ id: uuid(), name: str(), rating: nullable(num()), city: nullable(str()), timezone: str() }), service: obj({ id: uuid(), name: str(), duration_minutes: int(), category: str(), icon: nullable(str()) }), vehicle: obj({ id: uuid(), registration_no: str(), make: nullable(str()), model: nullable(str()), colour: nullable(str()) }), work_order: nullable(ref('WorkOrderSummary')) }),
  TimelineEntry: obj({ key: str(), title: str(), state: enumOf(['done', 'current', 'pending', 'blocked', 'skipped']), at: nullable(dt()) }),
  BookingDetail: { allOf: [ref('Booking'), obj({ payment: nullable(obj({ id: uuid(), status: enumOf(paymentStatus), receipt_no: nullable(str()), amount_cents: int() })), timeline: arr(ref('TimelineEntry')) })] },
  BookingCreate: obj({ vehicle_id: uuid(), outlet_id: uuid(), service_id: uuid(), slot_start: dt(), client_op_id: str(), notes: nullable(str()), customer_id: str({ description: 'Staff only: book on behalf of a customer' }) }, ['vehicle_id', 'outlet_id', 'service_id', 'slot_start', 'client_op_id']),
  WorkOrder: obj({ id: uuid(), ref: str({ example: 'WO-2026-4821' }), outlet_id: uuid(), booking_id: nullable(uuid()), quotation_id: nullable(uuid()), vehicle_id: uuid(), customer_id: str(), service_id: uuid(), status: enumOf(workStatus), priority: int({ minimum: 1, maximum: 3 }), bay: nullable(str()), checklist_template_id: nullable(uuid()), template_version: nullable(int()), assignee_id: nullable(str()), eta_at: nullable(dt()), started_at: nullable(dt()), blocked_reason: nullable(str()), completed_at: nullable(dt()), verified_at: nullable(dt()), verified_by: nullable(str()), due_at: nullable(dt()), pickup_otp: nullable(str({ description: '5-digit collection OTP — present only for the owning customer while the work order is verified and not yet collected; always null for staff', example: '48213' })), pickup_otp_issued_at: nullable(dt()), pickup_otp_verified_at: nullable(dt()), pickup_otp_verified_by: nullable(str()), collected_at: nullable(dt()), created_at: dt(), updated_at: dt() }),
  Task: obj({ id: uuid(), work_order_id: uuid(), outlet_id: uuid(), title: str(), seq: int(), assignee_id: nullable(str()), status: enumOf(workStatus), priority: int(), blocked_reason: nullable(str()), due_at: nullable(dt()), started_at: nullable(dt()), completed_at: nullable(dt()), elapsed_seconds: int(), client_op_id: nullable(str()), created_at: dt(), updated_at: dt() }),
  TaskExpanded: { allOf: [ref('Task'), obj({ work_order: nullable(obj({ id: uuid(), ref: str(), status: enumOf(workStatus), bay: nullable(str()), priority: int(), eta_at: nullable(dt()), due_at: nullable(dt()), blocked_reason: nullable(str()), vehicle: obj({ id: uuid(), registration_no: str(), make: nullable(str()), model: nullable(str()) }), service: obj({ id: uuid(), name: str(), category: str() }), progress: obj({ steps_done: int(), step_count: int() }) })), assignee: nullable(obj({ id: str(), full_name: str() })) })] },
  ChecklistStep: obj({ key: str(), title: str(), type: enumOf(['confirm', 'text', 'numeric', 'select', 'photo', 'ack', 'supervisor_verify']), required: bool(), hint: str(), options: arr(str()), unit: str(), min: num(), max: num(), photo_required: bool() }, ['key', 'title', 'type']),
  StepResult: obj({ id: uuid(), work_order_id: uuid(), step_key: str(), status: enumOf(['pending', 'done', 'blocked', 'skipped']), value: {}, attachment_id: nullable(uuid()), actor_id: nullable(str()), note: nullable(str()), client_op_id: nullable(str()), completed_at: nullable(dt()), updated_at: dt() }),
  TaskEvent: obj({ id: uuid(), task_id: nullable(uuid()), work_order_id: nullable(uuid()), actor_id: nullable(str()), event: str({ enum: ['assigned', 'transition', 'step_done', 'step_blocked', 'step_skipped', 'override'] }), from_status: nullable(str()), to_status: nullable(str()), reason: nullable(str()), metadata: { type: 'object', additionalProperties: true }, created_at: dt() }),
  WorkOrderDetail: obj({ work_order: { allOf: [ref('WorkOrder'), obj({ steps_done: int(), step_count: int(), progress_pct: int(), stage: int() })] }, template: nullable(obj({ id: uuid(), name: str(), version: int(), steps: arr(ref('ChecklistStep')) })), results: arr(ref('StepResult')), events: arr(ref('TaskEvent')), task: nullable(ref('Task')), timeline: arr(ref('TimelineEntry')) }),
  TransitionRequest: obj({ to: enumOf(['in_progress', 'blocked', 'completed', 'verified', 'cancelled']), reason: nullable(str()), client_op_id: str(), override: nullable(obj({ reason: str() }, ['reason'])) }, ['to']),
  TransitionResult: obj({ task: ref('Task'), work_order: ref('WorkOrder'), duplicate: bool(), side_effects: { type: 'object', additionalProperties: true } }),
  StepRequest: obj({ status: enumOf(['done', 'blocked', 'skipped']), value: {}, attachment_id: nullable(uuid()), note: nullable(str()), client_op_id: str() }, ['status']),
  StepResponse: obj({ result: ref('StepResult'), duplicate: bool(), progress: obj({ steps_done: int(), step_count: int(), progress_pct: int(), stage: int() }) }),
  Quotation: obj({ id: uuid(), ref: str({ example: 'QT-2026-0041' }), customer_id: str(), vehicle_id: uuid(), outlet_id: uuid(), category: str(), description: str(), status: enumOf(quotationStatus), amount_cents: nullable(int()), line_items: arr(ref('LineItem')), assessor_id: nullable(str()), valid_until: nullable(date()), quoted_at: nullable(dt()), decided_at: nullable(dt()), decision_by: nullable(str()), decision_note: nullable(str()), client_op_id: nullable(str()), created_at: dt(), updated_at: dt() }),
  LineItem: obj({ label: str(), amount_cents: int() }, ['label', 'amount_cents']),
  Attachment: obj({ id: uuid(), entity_type: str(), entity_id: uuid(), storage_path: str(), mime_type: str(), size_bytes: int(), sha256: nullable(str()), uploaded_by: nullable(str()), created_at: dt() }),
  PaymentMethod: obj({ id: uuid(), provider: str(), brand: nullable(str()), last4: nullable(str()), label: nullable(str()), is_default: bool(), created_at: dt() }),
  Payment: obj({ id: uuid(), booking_id: nullable(uuid()), quotation_id: nullable(uuid()), customer_id: str(), provider: str(), provider_ref: nullable(str()), method_id: nullable(uuid()), amount_cents: int(), currency: str(), status: enumOf(paymentStatus), receipt_no: nullable(str({ example: 'RCP-70001' })), idempotency_key: str(), failure_reason: nullable(str()), verified_at: nullable(dt()), created_at: dt(), updated_at: dt() }),
  ProviderEvent: obj({ id: str(), type: enumOf(['payment.succeeded', 'payment.failed', 'payment.refunded', 'payment.cancelled']), payment_id: uuid(), provider_ref: nullable(str()), amount_cents: int(), reason: nullable(str()), created_at: dt() }, ['id', 'type', 'payment_id']),
  LoyaltyTier: obj({ tier: enumOf(tiers), name: str(), min_points: int(), max_points: nullable(int()), earn_multiplier: num(), discount_pct: num() }, ['tier', 'name', 'min_points', 'earn_multiplier', 'discount_pct']),
  LoyaltyRules: { type: 'object', properties: { points_per_rand: num(), award_on: str(), idempotent_award: bool(), expiry_months: nullable(int()), birthday_bonus: { type: 'object', additionalProperties: true }, referral_bonus: { type: 'object', additionalProperties: true } }, required: ['points_per_rand'], additionalProperties: true },
  LoyaltyConfig: obj({ id: uuid(), version: int(), status: enumOf(['draft', 'published', 'archived']), tiers: arr(ref('LoyaltyTier')), rules: ref('LoyaltyRules'), change_note: nullable(str()), created_by: nullable(str()), published_by: nullable(str()), published_at: nullable(dt()), created_at: dt() }),
  LoyaltyAccount: obj({ customer_id: str(), tier: enumOf(tiers), balance_points: int({ description: 'Computed from the ledger (authoritative)' }), lifetime_points: int(), tier_since: nullable(dt()), updated_at: dt() }),
  LedgerEntry: obj({ id: uuid(), customer_id: str(), delta: int(), type: enumOf(['earn', 'redeem', 'adjust', 'expire', 'bonus']), source_type: nullable(str()), source_id: nullable(uuid()), reference: nullable(str()), description: nullable(str()), idempotency_key: str(), expires_at: nullable(dt()), created_at: dt() }),
  Reward: obj({ id: uuid(), name: str(), description: nullable(str()), icon: nullable(str()), points_cost: int(), min_tier: enumOf(tiers), is_active: bool(), sort_order: int(), eligible: bool(), affordable: bool() }),
  Redemption: obj({ ledger_id: uuid(), redemption: obj({ id: uuid(), code: str({ example: 'RW-1182' }), status: str(), reward_id: uuid(), created_at: dt() }), balance_after: int() }),
  InventoryItem: obj({ id: uuid(), outlet_id: uuid(), sku: str(), name: str(), unit: str(), on_hand: num(), reorder_threshold: num(), pack_size: nullable(num()), is_active: bool(), updated_at: dt(), alert: nullable(obj({ id: uuid(), level: enumOf(['low', 'out']), status: enumOf(['open', 'acknowledged', 'resolved']), created_at: dt() })) }),
  MovementRequest: obj({ delta: num(), reason: enumOf(['usage', 'receive', 'adjust', 'reorder_request', 'count']), note: nullable(str()), work_order_id: nullable(uuid()), client_op_id: str() }, ['delta', 'reason']),
  MovementResult: obj({ movement: { type: 'object', additionalProperties: true }, item: ref('InventoryItem'), duplicate: bool() }),
  Notification: obj({ id: uuid(), channel: enumOf(['push', 'whatsapp', 'sms', 'email']), template_key: str(), title: nullable(str()), body: str(), payload: { type: 'object', additionalProperties: true }, status: enumOf(['queued', 'sent', 'delivered', 'failed', 'suppressed']), read_at: nullable(dt()), sent_at: nullable(dt()), created_at: dt() }),
  AdminNotification: obj({ id: uuid(), recipient_id: str(), recipient_name: nullable(str()), channel: enumOf(['push', 'whatsapp', 'sms', 'email']), template_key: str(), title: nullable(str()), body: str(), status: enumOf(['queued', 'sent', 'delivered', 'failed', 'suppressed']), provider_ref: nullable(str({ description: 'Twilio Message SID (SM…) for WhatsApp' })), provider_status: nullable(str({ description: 'Raw provider status: queued|accepted|sending|sent|delivered|read|failed|undelivered' })), provider_error_code: nullable(str({ example: '63016' })), error: nullable(str()), attempts: int(), sent_at: nullable(dt()), delivered_at: nullable(dt()), read_by_recipient_at: nullable(dt()), read_at: nullable(dt()), created_at: dt(), updated_at: dt() }),
  NotificationFull: obj({ id: uuid(), recipient_id: str(), channel: enumOf(['push', 'whatsapp', 'sms', 'email']), template_key: str(), title: nullable(str()), body: str(), payload: { type: 'object', additionalProperties: true, description: 'Deep-link payload; `vars` holds the render context used for resend' }, status: enumOf(['queued', 'sent', 'delivered', 'failed', 'suppressed']), dedupe_key: nullable(str()), provider_ref: nullable(str()), provider_status: nullable(str()), provider_error_code: nullable(str()), error: nullable(str()), attempts: int(), sent_at: nullable(dt()), delivered_at: nullable(dt()), read_by_recipient_at: nullable(dt()), read_at: nullable(dt()), created_at: dt(), updated_at: dt() }),
  NotifyOutcome: obj({ channel: enumOf(['push', 'whatsapp', 'sms', 'email']), status: enumOf(['queued', 'sent', 'delivered', 'failed', 'suppressed', 'duplicate', 'no_template']), id: uuid() }),
  TwilioStatusCallback: obj({ MessageSid: str({ example: 'SM0123456789abcdef0123456789abcdef' }), MessageStatus: enumOf(['queued', 'accepted', 'scheduled', 'sending', 'sent', 'delivered', 'read', 'failed', 'undelivered']), SmsStatus: str(), ErrorCode: str({ example: '63016' }), ErrorMessage: str(), AccountSid: str(), From: str(), To: str() }, ['MessageSid']),
  SyncOperation: obj({ client_op_id: str(), kind: enumOf(['task.transition', 'step.result', 'inventory.movement', 'booking.create', 'quotation.create', 'vehicle.create']), payload: { type: 'object', additionalProperties: true }, device_time: dt() }, ['client_op_id', 'kind', 'payload']),
  SyncResult: obj({ client_op_id: str(), status: enumOf(['applied', 'conflict', 'rejected']), result: { description: 'Operation result, or {error, server_state} for conflict/rejected' } }),
  AuditEvent: obj({ id: uuid(), actor_id: nullable(str()), actor_role: nullable(str()), action: str(), entity_type: str(), entity_id: nullable(str()), outlet_id: nullable(uuid()), before: {}, after: {}, correlation_id: nullable(str()), outcome: str(), created_at: dt() }),
  Kpis: obj({ range: obj({ from: dt(), to: dt() }), revenue_cents: int(), revenue_previous_cents: int(), revenue_trend_pct: nullable(num()), bookings_today: int(), active_work_orders: int(), completed_today: int(), exceptions_count: int(), exceptions_breakdown: obj({ blocked: int(), overdue: int(), stock_alerts: int(), failed_payments: int() }), bookings_by_hour: arr(obj({ hour: int(), car_wash: int(), auto_body: int() })), revenue_by_outlet: arr(obj({ outlet_id: uuid(), name: str(), revenue_cents: int() })), top_staff: arr(obj({ staff_id: str(), name: str(), points: int(), rank: int() })) }),
  ExceptionItem: obj({ type: enumOf(['blocked', 'overdue', 'low_stock', 'out_of_stock', 'failed_payment']), severity: enumOf(['high', 'medium', 'low']), title: str(), detail: nullable(str()), outlet_id: nullable(uuid()), at: nullable(dt()), link: obj({ type: str(), id: str() }) }),
  ActivityItem: obj({ id: uuid(), type: enumOf(['task_event', 'payment_event', 'loyalty', 'inventory_alert']), at: dt(), title: str(), detail: nullable(str()), outlet_id: nullable(uuid()), link: nullable(obj({ type: str(), id: str() })) }),
  StaffPerformanceRow: obj({ staff_id: str(), name: str(), role: str(), tasks_completed: int(), tasks_verified: int(), avg_cycle_minutes: nullable(num()), checklist_compliance_pct: nullable(num()), points: int() }),
  ChecklistTemplate: obj({ id: uuid(), name: str(), category: enumOf(['car_wash', 'auto_body']), version: int(), status: enumOf(['draft', 'published', 'archived']), steps: arr(ref('ChecklistStep')), outlet_id: nullable(uuid()), created_by: nullable(str()), created_at: dt() }),
  FeatureFlag: obj({ key: str(), enabled: bool(), description: nullable(str()), updated_at: dt() }),
  OutletService: obj({ outlet_id: uuid(), service_id: uuid(), price_cents: nullable(int({ description: 'null = inherit the service base price' })), is_available: bool() }, ['outlet_id', 'service_id', 'price_cents', 'is_available']),
  AdminPayment: obj({ id: uuid(), booking_id: nullable(uuid()), booking_ref: nullable(str({ example: 'SPK-2026-0091' })), outlet_id: nullable(uuid()), outlet_name: nullable(str()), customer_id: str(), customer_name: str(), provider: str(), method_brand: nullable(str({ example: 'visa' })), method_last4: nullable(str({ example: '4242' })), amount_cents: int(), currency: str(), status: enumOf(paymentStatus), receipt_no: nullable(str({ example: 'RCP-70001' })), failure_reason: nullable(str()), verified_at: nullable(dt()), created_at: dt() }, ['id', 'customer_id', 'customer_name', 'provider', 'amount_cents', 'currency', 'status', 'created_at']),
  ReportSummary: obj({
    range: obj({ from: dt(), to: dt(), outlet_ids: nullable(arr(uuid())) }),
    financial: obj({ revenue_cents: int({ description: 'Sum of successful payments created in range' }), refunds_cents: int(), payments_total: int(), payments_successful: int(), payments_failed: int(), avg_ticket_cents: int(), by_status: arr(obj({ status: enumOf(paymentStatus), count: int(), amount_cents: int() })), by_outlet: arr(obj({ outlet_id: uuid(), name: str(), revenue_cents: int(), bookings: int() })), by_service: arr(obj({ service_id: uuid(), name: str(), category: str(), revenue_cents: int(), count: int() })) }),
    operational: obj({ bookings: int(), created: int(), pending: int(), confirmed: int(), in_service: int(), completed: int(), cancelled: int(), work_orders_completed: int(), on_time_pct: num(), avg_cycle_minutes: num(), checklist_compliance_pct: num(), quotes: obj({ requested: int(), quoted: int(), accepted: int(), declined: int(), expired: int(), converted: int() }) }),
    loyalty: obj({ points_issued: int(), points_redeemed: int(), points_expired: int(), ledger_entries: int(), outlet_scoped: bool() }),
    inventory: obj({ items_active: int(), items_below_threshold: int(), items_out_of_stock: int(), open_alerts: int() }),
    notifications: obj({ total: int(), delivered: int(), failed: int(), suppressed: int(), delivery_rate_pct: num({ description: 'delivered / (total − suppressed)' }), outlet_scoped: bool() }),
  }, ['range', 'financial', 'operational', 'loyalty', 'inventory', 'notifications']),
  IntegrationCard: { type: 'object', properties: { key: enumOf(['supabase', 'firebase', 'payments', 'whatsapp']), name: str(), status: enumOf(['connected', 'sandbox', 'disabled', 'error']), detail: str(), icon: str() }, required: ['key', 'name', 'status', 'detail', 'icon'], additionalProperties: true, description: 'Per-key extras: supabase {ok, latency_ms, url}; firebase {project_id, emulator}; payments {provider, sandbox, sandbox_confirm_enabled}; whatsapp {enabled, provider: twilio|sandbox, configured, messaging_service (masked MG… SID), status_callback}' },
  LeaderboardRow: obj({ staff_id: str(), name: str(), points: int(), rank: int(), delta: int({ description: 'Rank change vs previous period (+ = moved up)' }) }),
};

const paths = {};
const add = (path, method, op) => {
  paths[path] ??= {};
  paths[path][method] = { responses: { ...common }, ...op, responses: { ...(op.responses ?? {}), ...common, ...(op.responses ?? {}) } };
  if (!paths[path][method].responses['200'] && !paths[path][method].responses['201'] && !paths[path][method].responses['204']) throw new Error(`no success response for ${method} ${path}`);
};
const T = { auth: 'Auth & profile', cat: 'Catalogue', veh: 'Vehicles', bk: 'Bookings', qt: 'Quotations', pay: 'Payments', loy: 'Loyalty', staff: 'Staff', inv: 'Inventory', adm: 'Admin', not: 'Notifications', sys: 'System' };

add('/health', 'get', { tags: [T.sys], operationId: 'getHealth', summary: 'Liveness probe', security: [], responses: { 200: json(obj({ ok: bool(), version: str(), service: str(), time: dt() })) } });

// Auth
add('/auth/session', 'post', { tags: [T.auth], operationId: 'postAuthSession', summary: 'Upsert profile, claim seeded profile by e-mail, set custom claims', requestBody: body(obj({ app: enumOf(['customer', 'staff', 'admin']), full_name: str(), phone: str() }, ['app'])), responses: { 200: json(obj({ profile: ref('Profile'), outlet_ids: arr(uuid()), claims_updated: bool() })) } });
add('/me', 'get', { tags: [T.auth], operationId: 'getMe', summary: 'Current profile, outlets and loyalty account', responses: { 200: json(obj({ profile: ref('Profile'), outlets: arr(ref('Outlet')), loyalty_account: nullable(ref('LoyaltyAccount')) })) } });
add('/me', 'patch', { tags: [T.auth], operationId: 'patchMe', summary: 'Update editable profile fields', requestBody: body(obj({ full_name: str(), phone: nullable(str()), avatar_url: nullable(str()), marketing_opt_in: bool(), whatsapp_opt_in: bool(), push_opt_in: bool(), locale: str(), reduced_motion: bool(), haptics: bool() })), responses: { 200: json(obj({ profile: ref('Profile') })) } });
add('/devices', 'post', { tags: [T.auth], operationId: 'postDevice', summary: 'Register an FCM device token', requestBody: body(obj({ token: str(), platform: enumOf(['android', 'ios', 'web']), app: enumOf(['customer', 'staff', 'admin']) }, ['token', 'platform', 'app'])), responses: { 201: json(obj({ device: { type: 'object', additionalProperties: true } }), 'Registered') } });
add('/devices/{token}', 'delete', { tags: [T.auth], operationId: 'deleteDevice', summary: 'Remove a device token', parameters: [p('token', str())], responses: { 204: { description: 'Removed' } } });

// Catalogue
add('/outlets', 'get', { tags: [T.cat], operationId: 'listOutlets', summary: 'Active outlets (optionally sorted by distance)', parameters: [q('lat', num()), q('lng', num())], responses: { 200: json(obj({ data: arr(ref('Outlet')) })) } });
add('/outlets/{id}/services', 'get', { tags: [T.cat], operationId: 'listOutletServices', summary: 'Services at an outlet with effective price and points estimate', parameters: [p('id')], responses: { 200: json(obj({ data: arr(ref('OutletService')), tier: enumOf(tiers) })) } });
add('/availability', 'get', { tags: [T.cat], operationId: 'getAvailability', summary: 'Bookable slots for a service at an outlet on a date', parameters: [q('outlet_id', uuid(), true), q('service_id', uuid(), true), q('date', date(), true)], responses: { 200: json(obj({ data: arr(ref('Slot')), outlet_id: uuid(), service_id: uuid(), date: date() })) } });

// Vehicles
add('/vehicles', 'get', { tags: [T.veh], operationId: 'listVehicles', summary: 'Own vehicles (customer) or search (staff)', parameters: [q('customer_id', str()), q('registration_no', str())], responses: { 200: json(obj({ data: arr(ref('Vehicle')) })) } });
add('/vehicles', 'post', { tags: [T.veh], operationId: 'createVehicle', summary: 'Add a vehicle (409 with existing_vehicle_id on duplicate unless force)', requestBody: body(ref('VehicleCreate')), responses: { 201: json(obj({ vehicle: ref('Vehicle') }), 'Created'), 200: json(obj({ vehicle: ref('Vehicle') }), 'Duplicate replay / forced merge') } });
add('/vehicles/{id}', 'patch', { tags: [T.veh], operationId: 'updateVehicle', summary: 'Update own vehicle', parameters: [p('id')], requestBody: body(ref('VehicleCreate')), responses: { 200: json(obj({ vehicle: ref('Vehicle') })) } });
add('/vehicles/{id}', 'delete', { tags: [T.veh], operationId: 'deleteVehicle', summary: 'Soft-delete own vehicle', parameters: [p('id')], responses: { 204: { description: 'Deactivated' } } });
add('/vehicles/parse-disc', 'post', { tags: [T.veh], operationId: 'parseDisc', summary: 'Server-side parse of an SA licence-disc PDF417 payload', requestBody: body(obj({ raw: str() }, ['raw'])), responses: { 200: json(obj({ vehicle: ref('ParsedDisc') })) } });

// Bookings
add('/bookings', 'get', { tags: [T.bk], operationId: 'listBookings', summary: 'Own bookings (customer) or outlet bookings (staff)', parameters: [...pageParams, q('status', str({ description: 'Comma-separated statuses' })), q('outlet_id', uuid()), q('customer_id', str()), q('from', dt()), q('to', dt())], responses: { 200: json(paged(ref('Booking'))) } });
add('/bookings', 'post', { tags: [T.bk], operationId: 'createBooking', summary: 'Create a booking (server-side pricing, slot validated)', requestBody: body(ref('BookingCreate')), responses: { 201: json(obj({ booking: ref('Booking'), duplicate: bool() }), 'Created'), 200: json(obj({ booking: ref('Booking'), duplicate: bool() }), 'Replay of the same client_op_id') } });
add('/bookings/{id}', 'get', { tags: [T.bk], operationId: 'getBooking', summary: 'Booking with payment and timeline', parameters: [p('id')], responses: { 200: json(ref('BookingDetail')) } });
add('/bookings/{id}/cancel', 'post', { tags: [T.bk], operationId: 'cancelBooking', summary: 'Cancel (allowed until in_service)', parameters: [p('id')], requestBody: body(obj({ reason: nullable(str()) }), false), responses: { 200: json(obj({ booking: ref('Booking') })) } });
add('/bookings/{id}/reschedule', 'post', { tags: [T.bk], operationId: 'rescheduleBooking', summary: 'Move to another available slot', parameters: [p('id')], requestBody: body(obj({ slot_start: dt() }, ['slot_start'])), responses: { 200: json(obj({ booking: ref('Booking') })) } });
add('/bookings/{id}/checkin', 'post', { tags: [T.bk], operationId: 'checkInBooking', summary: 'Staff check-in: creates work order + task, status in_service', parameters: [p('id')], requestBody: body(obj({ bay: nullable(str()), priority: int({ minimum: 1, maximum: 3 }) }), false), responses: { 201: json(obj({ booking: ref('Booking'), work_order: ref('WorkOrder'), task: ref('Task'), created: bool() }), 'Work order created'), 200: json(obj({ booking: ref('Booking'), work_order: ref('WorkOrder'), task: ref('Task'), created: bool() }), 'Already checked in') } });

// Quotations
add('/quotations', 'get', { tags: [T.qt], operationId: 'listQuotations', summary: 'Own (customer) or outlet (staff) quotations', parameters: [...pageParams, q('status', str()), q('outlet_id', uuid())], responses: { 200: json(paged(ref('Quotation'))) } });
add('/quotations', 'post', { tags: [T.qt], operationId: 'createQuotation', summary: 'Request a repair quotation', requestBody: body(obj({ vehicle_id: uuid(), outlet_id: uuid(), category: enumOf(['Dent', 'Scratch', 'Bumper', 'Panel', 'Paint', 'Glass', 'Other']), description: str(), client_op_id: str(), attachment_ids: arr(uuid()) }, ['vehicle_id', 'outlet_id', 'category', 'description', 'client_op_id'])), responses: { 201: json(obj({ quotation: ref('Quotation'), duplicate: bool() }), 'Created'), 200: json(obj({ quotation: ref('Quotation'), duplicate: bool() }), 'Replay') } });
add('/quotations/{id}', 'get', { tags: [T.qt], operationId: 'getQuotation', summary: 'Quotation with attachments', parameters: [p('id')], responses: { 200: json({ allOf: [ref('Quotation'), obj({ attachments: arr(ref('Attachment')), work_order: nullable(obj({ id: uuid(), ref: str(), status: str() })) })] }) } });
add('/quotations/{id}/attachments', 'post', { tags: [T.qt], operationId: 'addQuotationAttachment', summary: 'Register an uploaded Cloud Storage object', parameters: [p('id')], requestBody: body(obj({ storage_path: str(), mime_type: str(), size_bytes: int(), sha256: nullable(str()) }, ['storage_path', 'mime_type', 'size_bytes'])), responses: { 201: json(obj({ attachment: ref('Attachment') }), 'Created') } });
add('/quotations/{id}/quote', 'post', { tags: [T.qt], operationId: 'quoteQuotation', summary: 'Supervisor/manager issues the quote (notifies customer)', parameters: [p('id')], requestBody: body(obj({ amount_cents: int(), line_items: arr(ref('LineItem')), valid_until: date() }, ['amount_cents', 'valid_until'])), responses: { 200: json(obj({ quotation: ref('Quotation') })) } });
add('/quotations/{id}/decision', 'post', { tags: [T.qt], operationId: 'decideQuotation', summary: 'Customer accepts or declines', parameters: [p('id')], requestBody: body(obj({ decision: enumOf(['accept', 'decline']), note: nullable(str()) }, ['decision'])), responses: { 200: json(obj({ quotation: ref('Quotation') })) } });
add('/quotations/{id}/convert', 'post', { tags: [T.qt], operationId: 'convertQuotation', summary: 'accepted → converted; creates work order + task', parameters: [p('id')], responses: { 201: json(obj({ quotation: ref('Quotation'), work_order: ref('WorkOrder'), task: ref('Task') }), 'Converted') } });

// Payments
add('/payments/methods', 'get', { tags: [T.pay], operationId: 'listPaymentMethods', summary: 'Tokenised payment methods', responses: { 200: json(obj({ data: arr(ref('PaymentMethod')) })) } });
add('/payments/methods', 'post', { tags: [T.pay], operationId: 'addPaymentMethod', summary: 'Store a provider token (never a PAN)', requestBody: body(obj({ provider_token: str(), brand: str(), last4: nullable(str()), label: str(), is_default: bool() }, ['provider_token', 'brand'])), responses: { 201: json(obj({ method: ref('PaymentMethod') }), 'Created') } });
add('/payments/intents', 'post', { tags: [T.pay], operationId: 'createPaymentIntent', summary: 'Create a payment intent for a booking', requestBody: body(obj({ booking_id: uuid(), method_id: nullable(uuid()), idempotency_key: str() }, ['booking_id', 'idempotency_key'])), responses: { 201: json(obj({ payment: ref('Payment'), client_secret: nullable(str()), redirect_url: nullable(str()) }), 'Created'), 200: json(obj({ payment: ref('Payment'), client_secret: nullable(str()), redirect_url: nullable(str()), duplicate: bool() }), 'Replay') } });
add('/payments/{id}/sandbox-confirm', 'post', { tags: [T.pay], operationId: 'sandboxConfirmPayment', summary: 'Simulate a signed provider webhook (flag payments_sandbox)', parameters: [p('id')], requestBody: body(obj({ outcome: enumOf(['succeeded', 'failed']) }), false), responses: { 200: json(obj({ payment: ref('Payment'), duplicate: bool() })) } });
add('/payments/webhook', 'post', { tags: [T.pay], operationId: 'paymentWebhook', summary: 'Provider webhook (HMAC-SHA256 in X-Signature; idempotent by event id)', security: [], parameters: [{ name: 'X-Signature', in: 'header', required: true, schema: str() }], requestBody: body(ref('ProviderEvent')), responses: { 200: json(obj({ received: bool(), duplicate: bool(), payment_id: uuid(), status: enumOf(paymentStatus), ignored: nullable(str()) })) } });
add('/payments/{id}', 'get', { tags: [T.pay], operationId: 'getPayment', summary: 'Payment with receipt', parameters: [p('id')], responses: { 200: json(obj({ payment: { allOf: [ref('Payment'), obj({ receipt: nullable(obj({ receipt_no: str(), amount_cents: int(), currency: str(), paid_at: nullable(dt()), provider: str(), provider_ref: nullable(str()) })) })] } })) } });

// Loyalty
add('/loyalty/account', 'get', { tags: [T.loy], operationId: 'getLoyaltyAccount', summary: 'Account, tier config and next tier', responses: { 200: json(obj({ account: ref('LoyaltyAccount'), tier_config: nullable(ref('LoyaltyTier')), tiers: arr(ref('LoyaltyTier')), next_tier: nullable(obj({ tier: enumOf(tiers), name: str(), points_needed: int() })), published_version: nullable(int()), rules: nullable(ref('LoyaltyRules')) })) } });
add('/loyalty/ledger', 'get', { tags: [T.loy], operationId: 'getLoyaltyLedger', summary: 'Ledger entries', parameters: pageParams, responses: { 200: json(paged(ref('LedgerEntry'))) } });
add('/loyalty/rewards', 'get', { tags: [T.loy], operationId: 'listRewards', summary: 'Rewards with eligibility by tier', responses: { 200: json(obj({ data: arr(ref('Reward')), balance_points: int(), tier: enumOf(tiers) })) } });
add('/loyalty/rewards/{id}/redeem', 'post', { tags: [T.loy], operationId: 'redeemReward', summary: 'Redeem (idempotent by Idempotency-Key)', parameters: [p('id'), { name: 'Idempotency-Key', in: 'header', required: true, schema: str() }], responses: { 201: json(ref('Redemption'), 'Redeemed (or replayed)') } });

// Staff
add('/tasks', 'get', { tags: [T.staff], operationId: 'listTasks', summary: 'Tasks by scope', parameters: [q('scope', enumOf(['mine', 'queue', 'done'])), q('outlet_id', uuid()), q('limit', int())], responses: { 200: json(obj({ data: arr(ref('TaskExpanded')), scope: str() })) } });
add('/tasks/{id}/transition', 'post', { tags: [T.staff], operationId: 'transitionTask', summary: 'Validated task transition (completed requires required steps; verified supervisor+)', parameters: [p('id')], requestBody: body(ref('TransitionRequest')), responses: { 200: json(ref('TransitionResult')) } });
add('/tasks/{id}/assign', 'post', { tags: [T.staff], operationId: 'assignTask', summary: 'Assign to a staff member (supervisor/manager)', parameters: [p('id')], requestBody: body(obj({ assignee_id: str(), reason: nullable(str()) }, ['assignee_id'])), responses: { 200: json(obj({ task: ref('Task') })) } });
add('/work-orders/{id}', 'get', { tags: [T.staff], operationId: 'getWorkOrder', summary: 'Work order with template, results, events and task', parameters: [p('id')], responses: { 200: json(ref('WorkOrderDetail')) } });
add('/work-orders/{id}/steps/{key}', 'post', { tags: [T.staff], operationId: 'recordStep', summary: 'Record a checklist step result (numeric min/max, photo requires attachment, supervisor_verify gated)', parameters: [p('id'), p('key', str())], requestBody: body(ref('StepRequest')), responses: { 200: json(ref('StepResponse')) } });
add('/work-orders/{id}/pickup/verify', 'post', { tags: [T.staff], operationId: 'verifyPickupOtp', summary: 'Staff confirm the collection OTP the customer presents → vehicle collected (409 invalid_otp with attempts_remaining; locked after 5 failures)', parameters: [p('id')], requestBody: body(obj({ otp: str({ pattern: '^\\d{5}$', example: '48213' }) }, ['otp'])), responses: { 200: json(obj({ work_order: ref('WorkOrder'), collected_at: dt(), collected: bool() })) } });
add('/work-orders/{id}/pickup/resend', 'post', { tags: [T.staff], operationId: 'resendPickupOtp', summary: 'Re-send the same collection OTP (push + WhatsApp pickup_otp template); rate-limited to once a minute per work order', parameters: [p('id')], responses: { 200: json(obj({ work_order: ref('WorkOrder'), notification: arr(ref('NotifyOutcome')), retry_after_seconds: int() })) } });
add('/sync/batch', 'post', { tags: [T.staff], operationId: 'syncBatch', summary: 'Replay the offline queue in order', requestBody: body(obj({ operations: arr(ref('SyncOperation')) }, ['operations'])), responses: { 200: json(obj({ results: arr(ref('SyncResult')), applied: int(), conflicts: int(), rejected: int() })) } });
add('/staff/ops-summary', 'get', { tags: [T.staff], operationId: 'getOpsSummary', summary: 'Supervisor ops summary', parameters: [q('outlet_id', uuid()), q('date', date())], responses: { 200: json(obj({ outlet_id: uuid(), date: date(), counts: obj({ in_progress: int(), queued: int(), blocked: int(), done: int() }), needs_attention: arr({ type: 'object', additionalProperties: true }), team_load: arr(obj({ staff_id: str(), name: str(), role: str(), availability: str(), capacity: int(), active_tasks: int() })) })) } });
add('/staff/team', 'get', { tags: [T.staff], operationId: 'getTeam', summary: 'Outlet team with skills, availability and load', parameters: [q('outlet_id', uuid())], responses: { 200: json(obj({ data: arr(obj({ id: str(), full_name: str(), role: str(), avatar_url: nullable(str()), is_primary: bool(), skills: arr(str()), availability: str(), capacity: int(), active_task_count: int() })) })) } });
add('/staff/leaderboard', 'get', { tags: [T.staff], operationId: 'getLeaderboard', summary: 'Points leaderboard and badges', parameters: [q('outlet_id', uuid()), q('period', enumOf(['week', 'month']))], responses: { 200: json(obj({ period: str(), period_start: dt(), rows: arr(ref('LeaderboardRow')), me: nullable(ref('LeaderboardRow')), badges: arr(obj({ badge: { type: 'object', additionalProperties: true }, earned_at: nullable(dt()) })) })) } });
add('/inventory', 'get', { tags: [T.inv], operationId: 'listInventory', summary: 'Items with open alert', parameters: [q('outlet_id', uuid())], responses: { 200: json(obj({ data: arr(ref('InventoryItem')), outlet_id: uuid() })) } });
add('/inventory/{id}/movements', 'post', { tags: [T.inv], operationId: 'recordMovement', summary: 'Record a movement (technician: usage/reorder_request; manager: any)', parameters: [p('id')], requestBody: body(ref('MovementRequest')), responses: { 201: json(ref('MovementResult'), 'Recorded'), 200: json(ref('MovementResult'), 'Replay') } });
add('/inventory/{id}', 'patch', { tags: [T.inv], operationId: 'updateInventoryItem', summary: 'Manager: threshold/name/unit (audited)', parameters: [p('id')], requestBody: body(obj({ reorder_threshold: num(), name: str(), unit: str() })), responses: { 200: json(obj({ item: ref('InventoryItem') })) } });

// Admin
add('/admin/kpis', 'get', { tags: [T.adm], operationId: 'getKpis', summary: 'Dashboard KPIs', parameters: [q('outlet_id', uuid()), q('from', dt()), q('to', dt())], responses: { 200: json(ref('Kpis')) } });
add('/admin/exceptions', 'get', { tags: [T.adm], operationId: 'getExceptions', summary: 'Blocked, overdue, stock and payment exceptions', parameters: [q('outlet_id', uuid())], responses: { 200: json(obj({ data: arr(ref('ExceptionItem')) })) } });
add('/admin/activity', 'get', { tags: [T.adm], operationId: 'getActivity', summary: 'Live activity feed', parameters: [q('outlet_id', uuid()), q('limit', int())], responses: { 200: json(obj({ data: arr(ref('ActivityItem')) })) } });
add('/admin/bookings', 'get', { tags: [T.adm], operationId: 'adminListBookings', summary: 'Live bookings table', parameters: [...pageParams, q('outlet_id', uuid()), q('date', date()), q('status', str()), q('search', str())], responses: { 200: json(paged({ type: 'object', additionalProperties: true })) } });
add('/admin/outlets', 'get', { tags: [T.adm], operationId: 'adminListOutlets', summary: 'All outlets', responses: { 200: json(obj({ data: arr(ref('Outlet')) })) } });
add('/admin/outlets', 'post', { tags: [T.adm], operationId: 'adminCreateOutlet', summary: 'Create outlet (audited)', requestBody: body(ref('Outlet')), responses: { 201: json(obj({ outlet: ref('Outlet') }), 'Created') } });
add('/admin/outlets/{id}', 'patch', { tags: [T.adm], operationId: 'adminUpdateOutlet', summary: 'Update outlet (audited)', parameters: [p('id')], requestBody: body(ref('Outlet')), responses: { 200: json(obj({ outlet: ref('Outlet') })) } });
add('/admin/outlets/{id}', 'delete', { tags: [T.adm], operationId: 'adminDeactivateOutlet', summary: 'Deactivate outlet', parameters: [p('id')], responses: { 204: { description: 'Deactivated' } } });
add('/admin/services', 'get', { tags: [T.adm], operationId: 'adminListServices', summary: 'All services', responses: { 200: json(obj({ data: arr(ref('Service')) })) } });
add('/admin/services', 'post', { tags: [T.adm], operationId: 'adminCreateService', summary: 'Create service (audited)', requestBody: body(ref('Service')), responses: { 201: json(obj({ service: ref('Service') }), 'Created') } });
add('/admin/services/{id}', 'patch', { tags: [T.adm], operationId: 'adminUpdateService', summary: 'Update service (audited)', parameters: [p('id')], requestBody: body(ref('Service')), responses: { 200: json(obj({ service: ref('Service') })) } });
add('/admin/services/{id}', 'delete', { tags: [T.adm], operationId: 'adminDeactivateService', summary: 'Deactivate service', parameters: [p('id')], responses: { 204: { description: 'Deactivated' } } });
add('/admin/outlets/{id}/services', 'get', { tags: [T.adm], operationId: 'adminListOutletServices', summary: 'Outlet service overrides', parameters: [p('id')], responses: { 200: json(obj({ data: arr({ type: 'object', additionalProperties: true }) })) } });
add('/admin/outlet-services', 'get', { tags: [T.adm], operationId: 'adminOutletServiceMatrix', summary: 'Outlet × service matrix (all outlets, or one visible outlet)', parameters: [q('outlet_id', uuid())], responses: { 200: json(obj({ data: arr(ref('OutletService')) })) } });
add('/admin/outlets/{id}/services/{serviceId}', 'put', { tags: [T.adm], operationId: 'adminUpsertOutletService', summary: 'Set outlet price / availability (audited)', parameters: [p('id'), p('serviceId')], requestBody: body(obj({ price_cents: nullable(int()), is_available: bool() })), responses: { 200: json(obj({ outlet_service: { type: 'object', additionalProperties: true } })) } });
add('/admin/outlets/{id}/services/{serviceId}', 'delete', { tags: [T.adm], operationId: 'adminDeleteOutletService', summary: 'Remove outlet service mapping', parameters: [p('id'), p('serviceId')], responses: { 204: { description: 'Removed' } } });
add('/admin/users', 'get', { tags: [T.adm], operationId: 'adminListUsers', summary: 'Staff users', parameters: [...pageParams, q('role', str()), q('search', str()), q('outlet_id', uuid())], responses: { 200: json(paged({ allOf: [ref('Profile'), obj({ staff_outlets: arr(obj({ outlet_id: uuid(), is_primary: bool() })), staff_skills: arr(obj({ skill: str() })) })] })) } });
add('/admin/users', 'post', { tags: [T.adm], operationId: 'adminInviteUser', summary: 'Create Firebase user + profile + outlets; sets claims', requestBody: body(obj({ email: str({ format: 'email' }), full_name: str(), role: enumOf(roles), phone: nullable(str()), outlet_ids: arr(uuid()), skills: arr(str()), invite: enumOf(['password', 'link']) }, ['email', 'full_name', 'role'])), responses: { 201: json(obj({ profile: ref('Profile'), uid: str(), temporary_password: nullable(str()), invite_link: nullable(str()) }), 'Created') } });
add('/admin/users/{id}', 'patch', { tags: [T.adm], operationId: 'adminUpdateUser', summary: 'Role/outlets/skills/is_active (is_active=false revokes refresh tokens)', parameters: [p('id', str())], requestBody: body(obj({ role: enumOf(roles), outlet_ids: arr(uuid()), skills: arr(str()), is_active: bool(), full_name: str(), phone: nullable(str()) })), responses: { 200: json(obj({ profile: ref('Profile'), outlet_ids: arr(uuid()) })) } });
add('/admin/customers', 'get', { tags: [T.adm], operationId: 'adminSearchCustomers', summary: 'Search customers (access logged)', parameters: [...pageParams, q('search', str())], responses: { 200: json(paged({ type: 'object', additionalProperties: true })) } });
add('/admin/customers/{id}', 'get', { tags: [T.adm], operationId: 'adminGetCustomer', summary: 'Customer 360 (access logged)', parameters: [p('id', str())], responses: { 200: json(obj({ customer: ref('Profile'), vehicles: arr(ref('Vehicle')), bookings: arr(ref('Booking')), loyalty_account: nullable(ref('LoyaltyAccount')), ledger: arr(ref('LedgerEntry')), payments: arr(ref('Payment')) })) } });
add('/admin/loyalty/config', 'get', { tags: [T.adm], operationId: 'getLoyaltyConfig', summary: 'Published and draft loyalty config', responses: { 200: json(obj({ published: nullable(ref('LoyaltyConfig')), draft: nullable(ref('LoyaltyConfig')) })) } });
add('/admin/loyalty/config/draft', 'put', { tags: [T.adm], operationId: 'putLoyaltyDraft', summary: 'Create/update the draft', requestBody: body(obj({ tiers: arr(ref('LoyaltyTier')), rules: ref('LoyaltyRules'), change_note: str() }, ['tiers', 'rules'])), responses: { 200: json(obj({ draft: ref('LoyaltyConfig') })) } });
add('/admin/loyalty/config/publish', 'post', { tags: [T.adm], operationId: 'publishLoyaltyConfig', summary: 'Admin: draft → published (previous archived, audited)', responses: { 200: json(obj({ published: ref('LoyaltyConfig'), archived: nullable(obj({ id: uuid(), version: int() })) })) } });
add('/admin/loyalty/config/discard', 'post', { tags: [T.adm], operationId: 'discardLoyaltyDraft', summary: 'Discard the draft', responses: { 200: json(obj({ discarded: obj({ id: uuid(), version: int() }) })) } });
add('/admin/inventory', 'get', { tags: [T.adm], operationId: 'adminListInventory', summary: 'Inventory across outlets', parameters: [q('outlet_id', uuid()), q('alerts_first', bool())], responses: { 200: json(obj({ data: arr(ref('InventoryItem')) })) } });
add('/admin/staff/performance', 'get', { tags: [T.adm], operationId: 'getStaffPerformance', summary: 'Tasks completed, cycle time, compliance, points', parameters: [q('outlet_id', uuid()), q('period', enumOf(['week', 'month', 'quarter']))], responses: { 200: json(obj({ period: str(), from: dt(), to: dt(), data: arr(ref('StaffPerformanceRow')) })) } });
add('/admin/templates', 'get', { tags: [T.adm], operationId: 'listTemplates', summary: 'Checklist templates', responses: { 200: json(obj({ data: arr(ref('ChecklistTemplate')) })) } });
add('/admin/templates', 'post', { tags: [T.adm], operationId: 'createTemplate', summary: 'Create template v1', requestBody: body(obj({ name: str(), category: enumOf(['car_wash', 'auto_body']), steps: arr(ref('ChecklistStep')), outlet_id: nullable(uuid()), status: enumOf(['draft', 'published']) }, ['name', 'category', 'steps'])), responses: { 201: json(obj({ template: ref('ChecklistTemplate') }), 'Created') } });
add('/admin/templates/{id}', 'put', { tags: [T.adm], operationId: 'versionTemplate', summary: 'Publish a new version (previous archived; services re-pointed)', parameters: [p('id')], requestBody: body(obj({ name: str(), category: enumOf(['car_wash', 'auto_body']), steps: arr(ref('ChecklistStep')), outlet_id: nullable(uuid()), status: enumOf(['draft', 'published']) }, ['steps'])), responses: { 201: json(obj({ template: ref('ChecklistTemplate'), previous: obj({ id: uuid(), version: int() }) }), 'New version') } });
add('/admin/audit', 'get', { tags: [T.adm], operationId: 'listAudit', summary: 'Audit events', parameters: [...pageParams, q('entity_type', str()), q('entity_id', str()), q('actor_id', str()), q('action', str())], responses: { 200: json(paged(ref('AuditEvent'))) } });
add('/admin/exports/{report}', 'get', { tags: [T.adm], operationId: 'exportCsv', summary: 'CSV export with metadata header lines (generated_at, filters, scope)', parameters: [p('report', str({ enum: ['bookings.csv', 'payments.csv', 'inventory.csv', 'staff_performance.csv', 'loyalty.csv'] })), q('outlet_id', uuid()), q('from', dateOrDt, false, 'YYYY-MM-DD (from 00:00Z) or ISO date-time; default 30 days ago'), q('to', dateOrDt, false, 'YYYY-MM-DD (to 23:59:59.999Z) or ISO date-time; default now')], responses: { 200: { description: 'CSV file', content: { 'text/csv': { schema: str() } } } } });
add('/admin/payments', 'get', { tags: [T.adm], operationId: 'adminListPayments', summary: 'Payments with booking ref, customer, method brand/last4 and receipt (finance-safe; same rows as payments.csv)', parameters: [q('outlet_id', uuid()), q('from', dateOrDt, false, 'YYYY-MM-DD or ISO date-time; default 30 days ago'), q('to', dateOrDt, false, 'YYYY-MM-DD or ISO date-time; default now'), q('status', str(), false, 'Comma-separated payment statuses'), q('limit', int({ minimum: 1, maximum: 200, default: 50 })), q('cursor', str())], responses: { 200: json({ allOf: [obj({ range: obj({ from: dt(), to: dt() }) }), paged(ref('AdminPayment'))] }) } });
add('/admin/reports/summary', 'get', { tags: [T.adm], operationId: 'getReportSummary', summary: 'Financial + operational summary computed from the same queries as the CSV exports (REP-005)', parameters: [q('outlet_id', uuid()), q('from', dateOrDt, false, 'YYYY-MM-DD or ISO date-time; default 30 days ago'), q('to', dateOrDt, false, 'YYYY-MM-DD or ISO date-time; default now')], responses: { 200: json(ref('ReportSummary')) } });
add('/admin/integrations', 'get', { tags: [T.adm], operationId: 'getIntegrations', summary: 'Integration status cards: Supabase probe, Firebase project, payments provider, WhatsApp', responses: { 200: json(obj({ data: arr(ref('IntegrationCard')) })) } });
add('/admin/notifications', 'get', { tags: [T.adm], operationId: 'adminListNotifications', summary: 'Delivery log across channels (provider status, error codes, receipts)', parameters: [...pageParams, q('status', str({ description: 'Comma-separated: queued|sent|delivered|failed|suppressed' })), q('channel', str({ description: 'Comma-separated: push|whatsapp|sms|email' })), q('recipient_id', str()), q('template_key', str())], responses: { 200: json(paged(ref('AdminNotification'))) } });
add('/admin/notifications/{id}/resend', 'post', { tags: [T.adm], operationId: 'adminResendNotification', summary: 'Re-send a failed/suppressed push or WhatsApp notification from its stored template + payload.vars (bumps attempts; audited)', parameters: [p('id')], responses: { 200: json(obj({ notification: ref('NotificationFull'), outcome: ref('NotifyOutcome') })) } });
add('/admin/flags', 'get', { tags: [T.adm], operationId: 'listFlags', summary: 'Feature flags', responses: { 200: json(obj({ data: arr(ref('FeatureFlag')), effective: { type: 'object', additionalProperties: bool() } })) } });
add('/admin/flags/{key}', 'patch', { tags: [T.adm], operationId: 'updateFlag', summary: 'Toggle a flag (audited)', parameters: [p('key', str())], requestBody: body(obj({ enabled: bool(), description: str() }, ['enabled'])), responses: { 200: json(obj({ flag: ref('FeatureFlag') })) } });

// Notifications
add('/notifications', 'get', { tags: [T.not], operationId: 'listNotifications', summary: 'Own notifications', parameters: pageParams, responses: { 200: json(paged(ref('Notification'))) } });
add('/notifications/{id}/read', 'post', { tags: [T.not], operationId: 'markNotificationRead', summary: 'Mark as read', parameters: [p('id')], responses: { 200: json(obj({ notification: obj({ id: uuid(), read_at: dt() }) })) } });
add('/notifications/twilio/status', 'post', { tags: [T.not], operationId: 'twilioStatusCallback', summary: 'Twilio delivery-status callback (form-encoded; X-Twilio-Signature validated against PUBLIC_API_BASE_URL/v1/notifications/twilio/status; idempotent by MessageSid)', security: [], parameters: [{ name: 'X-Twilio-Signature', in: 'header', required: true, schema: str() }], requestBody: { required: true, content: { 'application/x-www-form-urlencoded': { schema: ref('TwilioStatusCallback') } } }, responses: { 200: json(obj({ ignored: bool(), reason: str(), notification_id: uuid(), status: enumOf(['queued', 'sent', 'delivered', 'failed', 'suppressed']), provider_status: str() })) } });

const spec = {
  openapi: '3.0.3',
  info: {
    title: 'Sparkling REST API',
    version: '1.0.0',
    description: 'Sparkling platform backend (SRS v1.0). All JSON, snake_case, ISO-8601 UTC timestamps, money in integer ZAR cents. Mutating routes accept `Idempotency-Key` (or `client_op_id` in the body); replays return the cached first response. Every response carries `X-Correlation-Id`. Clients send `X-Client-App` and `X-Client-Version`.',
    contact: { name: 'Sparkling engineering', email: 'dev@sparkling.co.za' },
    license: { name: 'Proprietary', url: 'https://sparkling.co.za/legal' },
  },
  servers: [
    { url: 'https://europe-west1-sparkling-4e89d.cloudfunctions.net/api/v1', description: 'dev (Cloud Functions 2nd gen)' },
    { url: 'http://127.0.0.1:5001/sparkling-4e89d/europe-west1/api/v1', description: 'Firebase emulator' },
  ],
  tags: Object.values(T).map((name) => ({ name, description: `${name} endpoints` })),
  security: [{ bearerAuth: [] }],
  paths,
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'Firebase ID token' } },
    parameters: {},
    responses: {
      ValidationError: errResp('validation_error (400)'),
      Unauthenticated: errResp('unauthenticated (401)'),
      Forbidden: errResp('forbidden (403)'),
      NotFound: errResp('not_found (404)'),
      Conflict: errResp('conflict / invalid_transition (409)'),
      RateLimited: errResp('rate_limited (429)'),
      Internal: errResp('internal (500) — never includes stack traces'),
    },
    schemas,
  },
};
delete spec.components.parameters;
fs.writeFileSync(require('node:path').join(__dirname, '..', 'openapi.yaml'), '# Generated by scripts/gen-openapi.cjs — edit that file, then `node scripts/gen-openapi.cjs`.\n' + yaml.dump(spec, { noRefs: true, lineWidth: 200 }));
console.log(`wrote openapi.yaml with ${Object.keys(paths).length} paths`);
