/* Generates openapi.yaml (API-012). Run: node scripts/gen-openapi.cjs */
const fs = require('node:fs');
const yaml = require('js-yaml');

const ERR = { $ref: '#/components/schemas/ErrorEnvelope' };
const errResp = (desc) => ({ description: desc, content: { 'application/json': { schema: ERR } } });
const common = {
  400: { $ref: '#/components/responses/ValidationError' },
  401: { $ref: '#/components/responses/Unauthenticated' },
  403: { $ref: '#/components/responses/Forbidden' },
  404: { $ref: '#/components/responses/NotFound' },
  409: { $ref: '#/components/responses/Conflict' },
  410: { $ref: '#/components/responses/Gone' },
  429: { $ref: '#/components/responses/RateLimited' },
  500: { $ref: '#/components/responses/Internal' },
};
const json = (schema, desc = 'OK') => ({ description: desc, content: { 'application/json': { schema } } });
const obj = (props, required) => ({ type: 'object', properties: props, ...(required ? { required } : {}) });
const str = (extra = {}) => ({ type: 'string', ...extra });
const int = (extra = {}) => ({ type: 'integer', ...extra });
const num = (extra = {}) => ({ type: 'number', ...extra });
const bool = () => ({ type: 'boolean' });
const uuid = () => str({ format: 'uuid' });
const dt = () => str({ format: 'date-time' });
const date = () => str({ format: 'date' });
const arr = (items) => ({ type: 'array', items });
const ref = (n) => ({ $ref: `#/components/schemas/${n}` });
const nullable = (s) => (s.$ref ? { type: 'object', allOf: [s], nullable: true } : { ...s, nullable: true });
const enumOf = (v) => str({ enum: v });
const q = (name, schema, required = false, description) => ({ name, in: 'query', required, schema, ...(description ? { description } : {}) });
const p = (name, schema = uuid()) => ({ name, in: 'path', required: true, schema });
const body = (schema, required = true) => ({ required, content: { 'application/json': { schema } } });
const dateOrDt = { type: 'string', description: 'YYYY-MM-DD or RFC 3339 date-time', example: '2026-09-01' };
const paged = (item) => obj({ data: arr(item), next_cursor: nullable(str()) }, ['data', 'next_cursor']);
const pageParams = [q('limit', int({ minimum: 1, maximum: 100, default: 25 })), q('cursor', str()), q('sort', str({ example: 'slot_start:desc' }))];

const roles = ['customer', 'technician', 'supervisor', 'manager', 'admin', 'finance'];
const bookingStatus = ['draft', 'pending', 'confirmed', 'in_service', 'completed', 'cancelled'];
const quotationStatus = ['requested', 'assessing', 'quoted', 'accepted', 'declined', 'expired', 'converted'];
const workStatus = ['queued', 'assigned', 'in_progress', 'blocked', 'completed', 'verified', 'cancelled'];
const paymentStatus = ['initiated', 'pending', 'successful', 'failed', 'cancelled', 'refunded'];
const tiers = ['silver', 'gold', 'platinum', 'black'];
const membershipStatus = ['pending', 'active', 'past_due', 'cancelled', 'expired'];
const discountScopes = ['plan_services', 'other_services', 'all_services', 'none'];
const vehicleSizes = ['small', 'large', 'bike'];
const pricingModes = ['from', 'fixed', 'by_quote'];
const vatModes = ['incl', 'excl'];
const serviceGroups = ['Car Wash Options', 'Combinations', 'Auto Body Repair'];

const schemas = {
  ErrorEnvelope: obj({ error: obj({ code: enumOf(['unauthenticated', 'forbidden', 'not_found', 'validation_error', 'conflict', 'invalid_transition', 'invalid_otp', 'gone', 'rate_limited', 'internal']), message: str(), details: { type: 'array', items: {} }, correlation_id: str() }, ['code', 'message', 'correlation_id']) }, ['error']),
  Profile: obj({ id: str({ description: 'Firebase UID' }), role: enumOf(roles), full_name: str(), email: nullable(str({ format: 'email' })), phone: nullable(str()), avatar_url: nullable(str()), is_active: bool(), marketing_opt_in: bool(), whatsapp_opt_in: bool(), push_opt_in: bool(), locale: str(), reduced_motion: bool(), haptics: bool(), last_seen_at: nullable(dt()), created_at: dt(), updated_at: dt() }, ['id', 'role', 'full_name']),
  Outlet: obj({ id: uuid(), code: str(), name: str(), address_line: nullable(str()), city: nullable(str()), province: nullable(str()), country: str(), latitude: nullable(num()), longitude: nullable(num()), phone: nullable(str()), email: nullable(str()), timezone: str(), opening_hours: { type: 'object', additionalProperties: true }, slot_minutes: int(), bay_count: int(), rating: nullable(num()), is_active: bool(), legal_name: nullable(str()), trading_as: nullable(str()), company_registration_no: nullable(str()), vat_number: nullable(str()), registered_office: nullable(str()), bank_details: nullable(obj({ financial_institution: nullable(str()), account_name: nullable(str()), branch: nullable(str()), branch_code: nullable(str()), account_number: nullable(str()), account_type: nullable(str()) })), distance_km: num({ description: 'Present when ?lat&lng supplied' }) }),
  Service: obj({ id: uuid(), code: str(), name: str(), description: nullable(str()), category: enumOf(['car_wash', 'auto_body']), duration_minutes: int(), base_price_cents: int({ description: 'Legacy single price, kept in step with price_small/general' }), is_quote_based: bool(), points_per_rand: num(), icon: nullable(str()), checklist_template_id: nullable(uuid()), is_active: bool(), sort_order: int(), group_name: enumOf(serviceGroups), pricing_mode: enumOf(pricingModes), vat_mode: enumOf(vatModes), price_small_cents: nullable(int()), price_large_cents: nullable(int()), price_general_cents: nullable(int({ description: 'Size-independent price (auto body)' })), is_addon: bool(), addon_group_name: nullable(enumOf(serviceGroups)), notes: nullable(str()) }),
  ServiceComponentInput: obj({ child_service_id: uuid(), quantity: int({ minimum: 1, default: 1 }), sort_order: int() }, ['child_service_id']),
  ServiceComponent: obj({ child_service_id: uuid(), code: str(), name: str(), quantity: int(), sort_order: int() }, ['child_service_id', 'code', 'name', 'quantity', 'sort_order']),
  AdminService: { allOf: [ref('Service'), obj({ components: arr(ref('ServiceComponent')) }, ['components'])] },
  ServiceInput: obj({ code: str(), name: str(), description: nullable(str()), category: enumOf(['car_wash', 'auto_body']), duration_minutes: int(), base_price_cents: int(), points_per_rand: num(), icon: nullable(str()), checklist_template_id: nullable(uuid()), is_active: bool(), sort_order: int(), group_name: enumOf(serviceGroups), pricing_mode: enumOf(pricingModes), vat_mode: enumOf(vatModes), price_small_cents: nullable(int()), price_large_cents: nullable(int()), price_general_cents: nullable(int()), is_addon: bool(), addon_group_name: nullable(enumOf(serviceGroups)), notes: nullable(str()), components: nullable(arr(ref('ServiceComponentInput'))) }),
  OutletServiceOffer: obj({ id: uuid({ description: 'Alias of service_id' }), service_id: uuid(), code: str(), name: str({ description: 'Outlet display_name ?? service name' }), service_name: str({ description: 'Canonical service name' }), display_name: nullable(str()), description: nullable(str()), group_name: enumOf(serviceGroups), category: enumOf(['car_wash', 'auto_body']), duration_minutes: int(), icon: nullable(str()), pricing_mode: enumOf(pricingModes), vat_mode: enumOf(vatModes), pricing_mode_override: nullable(enumOf(pricingModes)), vat_mode_override: nullable(enumOf(vatModes)), is_quote_based: bool(), price_small_cents: nullable(int()), price_large_cents: nullable(int()), price_general_cents: nullable(int()), price_from_cents: nullable(int({ description: 'Lowest non-null price; null when by-quote' })), price_for: obj({ small: nullable(int()), large: nullable(int()), bike: nullable(int()) }, ['small', 'large', 'bike']), price_label: str({ example: 'From R 150' }), is_addon: bool(), addon_group_name: nullable(enumOf(serviceGroups)), includes: arr(obj({ service_id: uuid(), code: str(), name: str(), quantity: int() })), included_in: arr(uuid()), components_source: enumOf(['outlet', 'global', 'none']), is_available: bool(), sort_order: int(), notes: nullable(str()), points_estimate: int(), price_cents: nullable(int({ description: 'Only with ?vehicle_size: price resolved for that size (base, before discount)' })), discount_cents: int(), vat_cents: int(), total_cents: nullable(int()), discount_label: nullable(str()) }, ['service_id', 'code', 'name', 'group_name', 'category', 'pricing_mode', 'vat_mode', 'price_from_cents', 'price_for', 'price_label', 'is_addon', 'includes', 'included_in', 'components_source', 'is_available', 'sort_order', 'points_estimate']),
  OutletServiceInput: obj({ display_name: nullable(str()), price_small_cents: nullable(int()), price_large_cents: nullable(int()), price_general_cents: nullable(int()), pricing_mode: nullable(enumOf(pricingModes)), vat_mode: nullable(enumOf(vatModes)), is_available: bool(), sort_order: nullable(int()), notes: nullable(str()), price_cents: nullable(int({ description: 'Legacy single price' })), components: nullable({ ...arr(ref('ServiceComponentInput')), description: 'Outlet-specific composition; null = use the global set' }) }),
  Slot: obj({ slot_start: dt(), slot_end: dt(), capacity: int(), booked: int(), available: bool() }),
  Vehicle: obj({ id: uuid(), customer_id: str(), registration_no: str(), vin: nullable(str()), engine_no: nullable(str()), make: nullable(str()), model: nullable(str()), colour: nullable(str()), year: nullable(int()), licence_no: nullable(str()), disc_expiry: nullable(date()), source: enumOf(['manual', 'scan']), disc_verified: bool(), disc_hash: nullable(str()), size_class: nullable(enumOf(vehicleSizes)), is_active: bool(), created_at: dt(), updated_at: dt() }),
  StaffCustomer: obj({ id: str({ description: 'Firebase UID, or walkin_<uuid> until claimed' }), full_name: str(), email: nullable(str({ format: 'email' })), phone: nullable(str()), marketing_opt_in: bool(), whatsapp_opt_in: bool(), loyalty: nullable(obj({ tier: enumOf(tiers), balance_points: int(), discount_pct: num(), plan_code: nullable(str({ example: 'gold' })), plan_name: nullable(str()), membership_status: nullable(enumOf(membershipStatus)), included_remaining: int({ description: 'Remaining monthly washes on the live plan (0 without one)' }) }, ['tier', 'balance_points'])), vehicles: arr(obj({ id: uuid(), registration_no: str(), make: nullable(str()), model: nullable(str()), colour: nullable(str()), disc_verified: bool() })) }, ['id', 'full_name', 'email', 'phone', 'marketing_opt_in', 'whatsapp_opt_in', 'loyalty', 'vehicles']),
  StaffCustomerCreate: obj({ full_name: str({ minLength: 2 }), phone: str({ description: 'Any SA/international format; stored as E.164 (082… → +2782…)' }), email: nullable(str({ format: 'email' })), marketing_opt_in: bool(), whatsapp_opt_in: bool(), outlet_id: uuid(), client_op_id: str() }, ['full_name', 'phone', 'client_op_id']),
  PosPaymentRecord: obj({ booking_id: uuid({ description: 'Exactly one of booking_id / quotation_id' }), quotation_id: uuid({ description: 'An accepted quotation (auto-body job)' }), method: enumOf(['cash', 'card_terminal']), reference: nullable(str({ maxLength: 64 })), amount_cents: int({ description: 'Must equal bookings.total_cents / quotations.amount_cents' }), idempotency_key: str() }, ['method', 'amount_cents', 'idempotency_key']),
  VehicleCreate: obj({ registration_no: str(), vin: nullable(str({ minLength: 17, maxLength: 17 })), make: nullable(str()), model: nullable(str()), colour: nullable(str()), year: nullable(int()), licence_no: nullable(str()), disc_expiry: nullable(date()), engine_no: nullable(str()), source: enumOf(['manual', 'scan']), disc_hash: nullable(str({ description: 'sha256 of the raw disc payload (raw is never stored)' })), force: bool(), client_op_id: str(), size_class: nullable(enumOf(vehicleSizes)), description: nullable(str({ description: 'Licence-disc description; only used to derive size_class when it is omitted' })) }, ['registration_no']),
  ParsedDisc: obj({ registration_no: str(), licence_no: nullable(str()), vehicle_register_no: nullable(str()), description: nullable(str()), make: nullable(str()), model: nullable(str()), colour: nullable(str()), vin: nullable(str()), engine_no: nullable(str()), disc_expiry: nullable(date()), disc_hash: str(), warnings: arr(str()), size_class: nullable(enumOf(vehicleSizes)), source: str({ enum: ['scan'] }) }),
  WorkOrderSummary: obj({ id: uuid(), ref: str(), status: enumOf(workStatus), stage: int(), stage_count: int(), progress_pct: int(), eta_at: nullable(dt()), assignee_name: nullable(str()), bay: nullable(str()), blocked_reason: nullable(str()), verified_at: nullable(dt()), pickup_otp_verified_at: nullable(dt()), collected_at: nullable(dt()), pickup_otp: str({ description: 'Only on GET /bookings/:id for the owning customer while the booking is completed and the vehicle uncollected; omitted otherwise', example: '48213' }), pickup_otp_issued_at: dt(), updated_at: dt() }),
  Booking: obj({ payment_method: nullable(enumOf(['card', 'eft', 'cash'])), id: uuid(), ref: str({ example: 'SPK-2026-0091' }), customer_id: str(), vehicle_id: uuid(), outlet_id: uuid(), service_id: uuid(), quotation_id: nullable(uuid()), slot_start: dt(), slot_end: dt(), status: enumOf(bookingStatus), price_cents: int(), discount_cents: int(), total_cents: int(), discount_label: nullable(str({ example: 'Gold −10%' })), points_pending: int(), notes: nullable(str()), cancel_reason: nullable(str()), client_op_id: nullable(str()), created_by: nullable(str({ description: 'Profile id of whoever created it (staff uid for walk-ins)' })), walk_in: bool(), vehicle_size: nullable(enumOf(vehicleSizes)), pricing_mode: nullable(enumOf(pricingModes)), vat_mode: nullable(enumOf(vatModes)), addon_service_ids: arr(uuid()), addons_cents: int(), membership_id: nullable(uuid()), entitlement_id: nullable(uuid()), membership_benefit: nullable(enumOf(['included', 'discount'])), addons: arr(obj({ service_id: uuid(), name: str(), price_cents: nullable(int()) })), price_label: str({ example: 'From R 459' }), created_at: dt(), updated_at: dt(), outlet: obj({ id: uuid(), name: str(), rating: nullable(num()), city: nullable(str()), timezone: str() }), service: obj({ id: uuid(), name: str(), duration_minutes: int(), category: str(), icon: nullable(str()) }), vehicle: obj({ id: uuid(), registration_no: str(), make: nullable(str()), model: nullable(str()), colour: nullable(str()) }), work_order: nullable(ref('WorkOrderSummary')) }),
  TimelineEntry: obj({ key: str(), title: str(), state: enumOf(['done', 'current', 'pending', 'blocked', 'skipped']), at: nullable(dt()) }),
  BookingDetail: { allOf: [ref('Booking'), obj({ payment: nullable(obj({ id: uuid(), status: enumOf(paymentStatus), receipt_no: nullable(str()), amount_cents: int() })), timeline: arr(ref('TimelineEntry')) })] },
  BookingCreate: obj({ vehicle_id: uuid(), outlet_id: uuid(), service_id: uuid(), slot_start: dt({ description: 'Required for app bookings; optional for staff walk-ins (defaults to now rounded up to the outlet slot grid)' }), client_op_id: str(), notes: nullable(str()), customer_id: str({ description: 'Staff only (required): book on behalf of a customer' }), walk_in: { type: 'boolean', description: 'Staff only: counter booking — starts confirmed; outlet must be in the staff member’s outlets' }, checkin: obj({ bay: nullable(str()), priority: int({ minimum: 1, maximum: 3 }) }, undefined), vehicle_size: enumOf(vehicleSizes), addon_service_ids: arr(uuid()) }, ['vehicle_id', 'outlet_id', 'service_id', 'client_op_id']),
  BookingCreated: obj({ booking: ref('Booking'), duplicate: bool(), work_order: nullable(ref('WorkOrder')), task: nullable(ref('Task')) }, ['booking', 'duplicate']),
  WorkOrder: obj({ id: uuid(), ref: str({ example: 'WO-2026-4821' }), outlet_id: uuid(), booking_id: nullable(uuid()), quotation_id: nullable(uuid()), vehicle_id: uuid(), customer_id: str(), service_id: uuid(), status: enumOf(workStatus), priority: int({ minimum: 1, maximum: 3 }), bay: nullable(str()), checklist_template_id: nullable(uuid()), template_version: nullable(int()), assignee_id: nullable(str()), eta_at: nullable(dt()), started_at: nullable(dt()), blocked_reason: nullable(str()), completed_at: nullable(dt()), verified_at: nullable(dt()), verified_by: nullable(str()), due_at: nullable(dt()), pickup_otp: nullable(str({ description: '5-digit collection OTP — present only for the owning customer while the work order is verified and not yet collected; always null for staff', example: '48213' })), pickup_otp_issued_at: nullable(dt()), pickup_otp_verified_at: nullable(dt()), pickup_otp_verified_by: nullable(str()), collected_at: nullable(dt()), created_at: dt(), updated_at: dt() }),
  Task: obj({ id: uuid(), work_order_id: uuid(), outlet_id: uuid(), title: str(), seq: int(), assignee_id: nullable(str()), status: enumOf(workStatus), priority: int(), blocked_reason: nullable(str()), due_at: nullable(dt()), started_at: nullable(dt()), completed_at: nullable(dt()), elapsed_seconds: int(), client_op_id: nullable(str()), created_at: dt(), updated_at: dt() }),
  TaskExpanded: { allOf: [ref('Task'), obj({ work_order: nullable(obj({ id: uuid(), ref: str(), status: enumOf(workStatus), bay: nullable(str()), priority: int(), eta_at: nullable(dt()), due_at: nullable(dt()), blocked_reason: nullable(str()), vehicle: obj({ id: uuid(), registration_no: str(), make: nullable(str()), model: nullable(str()) }), service: obj({ id: uuid(), name: str(), category: str() }), progress: obj({ steps_done: int(), step_count: int() }) })), assignee: nullable(obj({ id: str(), full_name: str() })) })] },
  ChecklistStep: obj({ key: str(), title: str(), type: enumOf(['confirm', 'text', 'numeric', 'select', 'photo', 'ack', 'supervisor_verify']), required: bool(), hint: str(), options: arr(str()), unit: str(), min: num(), max: num(), photo_required: bool() }, ['key', 'title', 'type']),
  StepResult: obj({ id: uuid(), work_order_id: uuid(), step_key: str(), status: enumOf(['pending', 'done', 'blocked', 'skipped']), value: {}, attachment_id: nullable(uuid()), actor_id: nullable(str()), note: nullable(str()), client_op_id: nullable(str()), completed_at: nullable(dt()), updated_at: dt() }),
  TaskEvent: obj({ id: uuid(), task_id: nullable(uuid()), work_order_id: nullable(uuid()), actor_id: nullable(str()), event: str({ enum: ['assigned', 'transition', 'step_done', 'step_blocked', 'step_skipped', 'override'] }), from_status: nullable(str()), to_status: nullable(str()), reason: nullable(str()), metadata: { type: 'object', additionalProperties: true }, created_at: dt() }),
  WorkOrderDetail: obj({ work_order: { allOf: [ref('WorkOrder'), obj({ steps_done: int(), step_count: int(), progress_pct: int(), stage: int() })] }, template: nullable(obj({ id: uuid(), name: str(), version: int(), steps: arr(ref('ChecklistStep')) })), results: arr(ref('StepResult')), events: arr(ref('TaskEvent')), task: nullable(ref('Task')), timeline: arr(ref('TimelineEntry')) }),
  TransitionRequest: obj({ to: enumOf(['in_progress', 'blocked', 'completed', 'verified', 'cancelled']), reason: nullable(str()), client_op_id: str(), override: nullable(obj({ reason: str() }, ['reason'])) }, ['to']),
  TransitionResult: obj({ task: ref('Task'), work_order: ref('WorkOrder'), duplicate: bool(), side_effects: { type: 'object', additionalProperties: true } }),
  StepRequest: obj({ status: enumOf(['done', 'blocked', 'skipped']), value: {}, attachment_id: nullable(uuid()), note: nullable(str()), client_op_id: str() }, ['status']),
  StepResponse: obj({ result: ref('StepResult'), duplicate: bool(), progress: obj({ steps_done: int(), step_count: int(), progress_pct: int(), stage: int() }) }),
  Quotation: obj({ id: uuid(), ref: str({ example: 'QT-2026-0041' }), customer_id: str(), vehicle_id: uuid(), outlet_id: uuid(), category: str(), description: str(), status: enumOf(quotationStatus), amount_cents: nullable(int()), line_items: arr(ref('LineItem')), items: { ...arr(ref('LineItem')), description: 'Alias of line_items' }, items_note: nullable(str()), assessor_id: nullable(str()), customer_name: nullable(str()), assessor_name: nullable(str()), work_order_ref: nullable(str({ description: 'Ref of the work order created by /convert (single-quotation responses)' })), valid_until: nullable(date()), quoted_at: nullable(dt()), decided_at: nullable(dt()), decision_by: nullable(str()), decision_by_name: nullable(str()), decision_note: nullable(str()), decision_source: nullable(enumOf(['app', 'public_link', 'staff'])), public_token_expires_at: nullable(dt()), public_url: nullable(str({ description: 'Staff only: ${PUBLIC_WEB_BASE_URL}/q/<token>; null when no base URL is configured. The token itself is never listed.' })), pdf_url: str({ example: '/v1/quotations/<id>/pdf' }), pdf_generated_at: nullable(dt()), attachments: arr(ref('QuotationAttachment')), client_op_id: nullable(str()), created_at: dt(), updated_at: dt() }),
  LineItem: obj({ label: str({ maxLength: 200 }), description: nullable(str({ maxLength: 500 })), category: nullable(str({ example: 'Bumper' })), service_id: nullable(uuid()), amount_cents: int({ minimum: 0, description: 'Line total (0 when a membership entitlement covers the service)' }), quantity: nullable(int({ minimum: 1 })), membership_benefit: nullable(enumOf(['included'])), entitlement_id: nullable(uuid()) }, ['label', 'amount_cents']),
  QuotationRaise: obj({ customer_id: str({ description: 'Active customer profile (Firebase UID or walkin_<uuid>)' }), vehicle_id: uuid(), outlet_id: uuid({ description: 'Must be one of the staff member’s outlets' }), category: enumOf(['Dent', 'Scratch', 'Bumper', 'Panel', 'Paint', 'Glass', 'Other']), description: str(), items: { ...arr(ref('LineItem')), minItems: 1, maxItems: 20 }, valid_until: date({ description: 'Today or later' }), items_note: nullable(str({ maxLength: 1000 })), client_op_id: str(), send_to_customer: { type: 'boolean', default: true, description: 'quote_ready push + WhatsApp (Content variables first_name, public_token)' } }, ['customer_id', 'vehicle_id', 'outlet_id', 'category', 'description', 'items', 'valid_until', 'client_op_id']),
  QuotationRequest: obj({ vehicle_id: uuid(), outlet_id: uuid(), category: enumOf(['Dent', 'Scratch', 'Bumper', 'Panel', 'Paint', 'Glass', 'Other']), description: str(), client_op_id: str(), attachment_ids: arr(uuid()) }, ['vehicle_id', 'outlet_id', 'category', 'description', 'client_op_id']),
  QuotationAttachment: obj({ id: uuid(), kind: enumOf(['damage_photo', 'document']), mime_type: str({ example: 'image/jpeg' }), size_bytes: int(), width: nullable(int()), height: nullable(int()), caption: nullable(str()), url: str({ description: 'API path that streams the file (signed-in: /v1/quotations/{id}/photos/{attachmentId}; public: /v1/public/quotations/{token}/photos/{attachmentId})' }), created_at: dt() }, ['id', 'kind', 'mime_type', 'size_bytes', 'url']),
  Attachment: obj({ id: uuid(), entity_type: str(), entity_id: uuid(), storage_path: str(), mime_type: str(), size_bytes: int(), sha256: nullable(str()), uploaded_by: nullable(str()), kind: enumOf(['damage_photo', 'document']), width: nullable(int()), height: nullable(int()), caption: nullable(str()), created_at: dt() }),
  PublicQuotation: obj({ ref: str(), status: enumOf(quotationStatus), outlet: nullable(obj({ name: str(), phone: nullable(str()), address_line: nullable(str()) })), customer: obj({ first_name: str() }), vehicle: nullable(obj({ registration_no: str(), make: nullable(str()), model: nullable(str()), colour: nullable(str()) })), items: arr(ref('LineItem')), amount_cents: nullable(int()), currency: str({ example: 'ZAR' }), valid_until: nullable(date()), quoted_at: nullable(dt()), decided_at: nullable(dt()), decision_source: nullable(enumOf(['app', 'public_link', 'staff'])), expired: bool(), can_decide: bool(), attachments: arr(obj({ id: uuid(), url: str(), caption: nullable(str()), width: nullable(int()), height: nullable(int()) })), pdf_url: str(), notes: nullable(str()) }, ['ref', 'status', 'customer', 'items', 'currency', 'expired', 'can_decide', 'attachments', 'pdf_url']),
  PublicDecision: obj({ decision: enumOf(['accept', 'decline']), note: nullable(str({ maxLength: 500 })), accepted_by_name: nullable(str({ maxLength: 120 })) }, ['decision']),
  PaymentMethod: obj({ id: uuid(), provider: str(), brand: nullable(str()), last4: nullable(str()), label: nullable(str()), is_default: bool(), created_at: dt() }),
  Payment: obj({ id: uuid(), booking_id: nullable(uuid()), quotation_id: nullable(uuid()), customer_id: str(), provider: str(), provider_ref: nullable(str()), method_id: nullable(uuid()), amount_cents: int(), currency: str(), status: enumOf(paymentStatus), receipt_no: nullable(str({ example: 'RCP-70001' })), idempotency_key: str(), failure_reason: nullable(str()), verified_at: nullable(dt()), method: nullable(enumOf(['cash', 'card_terminal', 'card', 'eft'])), recorded_by: nullable(str({ description: 'Staff uid for POS attestations' })), membership_invoice_id: nullable(uuid({ description: 'Set for membership invoice payments (booking_id null)' })), created_at: dt(), updated_at: dt() }),
  ProviderEvent: obj({ id: str(), type: enumOf(['payment.succeeded', 'payment.failed', 'payment.refunded', 'payment.cancelled']), payment_id: uuid(), provider_ref: nullable(str()), amount_cents: int(), reason: nullable(str()), created_at: dt() }, ['id', 'type', 'payment_id']),
  LoyaltyTier: obj({ tier: enumOf(tiers), name: str(), min_points: int(), max_points: nullable(int()), earn_multiplier: num(), discount_pct: num() }, ['tier', 'name', 'min_points', 'earn_multiplier', 'discount_pct']),
  LoyaltyRules: { type: 'object', properties: { points_per_rand: num(), award_on: str(), idempotent_award: bool(), expiry_months: nullable(int()), birthday_bonus: { type: 'object', additionalProperties: true }, referral_bonus: { type: 'object', additionalProperties: true } }, required: ['points_per_rand'], additionalProperties: true },
  LoyaltyConfig: obj({ id: uuid(), version: int(), status: enumOf(['draft', 'published', 'archived']), tiers: arr(ref('LoyaltyTier')), rules: ref('LoyaltyRules'), change_note: nullable(str()), created_by: nullable(str()), published_by: nullable(str()), published_at: nullable(dt()), created_at: dt() }),
  LoyaltyAccount: obj({ customer_id: str(), tier: enumOf(tiers), balance_points: int({ description: 'Computed from the ledger (authoritative)' }), lifetime_points: int(), tier_since: nullable(dt()), updated_at: dt() }),
  LedgerEntry: obj({ id: uuid(), customer_id: str(), delta: int(), type: enumOf(['earn', 'redeem', 'adjust', 'expire', 'bonus']), source_type: nullable(str()), source_id: nullable(uuid()), reference: nullable(str()), description: nullable(str()), idempotency_key: str(), expires_at: nullable(dt()), created_at: dt() }),
  Reward: obj({ id: uuid(), name: str(), description: nullable(str()), icon: nullable(str()), points_cost: int(), min_tier: enumOf(tiers), is_active: bool(), sort_order: int(), eligible: bool(), affordable: bool() }),
  Redemption: obj({ ledger_id: uuid(), redemption: obj({ id: uuid(), code: str({ example: 'RW-1182' }), status: str(), reward_id: uuid(), created_at: dt() }), balance_after: int() }),
  InventoryItem: obj({ id: uuid(), outlet_id: uuid(), outlet_name: str(), sku: str(), name: str(), unit: str(), on_hand: num(), reorder_threshold: num(), pack_size: nullable(num()), capacity: num({ description: 'Suggested full level for the stock bar (≥ on_hand)' }), blocking_work_orders: int({ description: 'Blocked work orders that logged usage of this item' }), is_active: bool(), updated_at: dt(), alert: nullable(obj({ id: uuid(), level: enumOf(['low', 'out']), status: enumOf(['open', 'acknowledged', 'resolved']), created_at: dt() })) }),
  MovementRequest: obj({ delta: num(), reason: enumOf(['usage', 'receive', 'adjust', 'reorder_request', 'count']), note: nullable(str()), work_order_id: nullable(uuid()), client_op_id: str() }, ['delta', 'reason']),
  MovementResult: obj({ movement: { type: 'object', additionalProperties: true }, item: ref('InventoryItem'), duplicate: bool() }),
  Notification: obj({ id: uuid(), channel: enumOf(['push', 'whatsapp', 'sms', 'email']), template_key: str(), title: nullable(str()), body: str(), payload: { type: 'object', additionalProperties: true }, status: enumOf(['queued', 'sent', 'delivered', 'failed', 'suppressed']), read_at: nullable(dt()), sent_at: nullable(dt()), created_at: dt() }),
  AdminNotification: obj({ id: uuid(), recipient_id: str(), recipient_name: nullable(str()), channel: enumOf(['push', 'whatsapp', 'sms', 'email']), template_key: str(), title: nullable(str()), body: str(), status: enumOf(['queued', 'sent', 'delivered', 'failed', 'suppressed']), provider_ref: nullable(str({ description: 'Twilio Message SID (SM…) for WhatsApp' })), provider_status: nullable(str({ description: 'Raw provider status: queued|accepted|sending|sent|delivered|read|failed|undelivered' })), provider_error_code: nullable(str({ example: '63016' })), error: nullable(str()), attempts: int(), sent_at: nullable(dt()), delivered_at: nullable(dt()), read_by_recipient_at: nullable(dt()), read_at: nullable(dt()), created_at: dt(), updated_at: dt() }),
  NotificationFull: obj({ id: uuid(), recipient_id: str(), channel: enumOf(['push', 'whatsapp', 'sms', 'email']), template_key: str(), title: nullable(str()), body: str(), payload: { type: 'object', additionalProperties: true, description: 'Deep-link payload; `vars` holds the render context used for resend' }, status: enumOf(['queued', 'sent', 'delivered', 'failed', 'suppressed']), dedupe_key: nullable(str()), provider_ref: nullable(str()), provider_status: nullable(str()), provider_error_code: nullable(str()), error: nullable(str()), attempts: int(), sent_at: nullable(dt()), delivered_at: nullable(dt()), read_by_recipient_at: nullable(dt()), read_at: nullable(dt()), created_at: dt(), updated_at: dt() }),
  NotifyOutcome: obj({ channel: enumOf(['push', 'whatsapp', 'sms', 'email']), status: enumOf(['queued', 'sent', 'delivered', 'failed', 'suppressed', 'duplicate', 'no_template']), id: uuid() }),
  TwilioStatusCallback: obj({ MessageSid: str({ example: 'SM0123456789abcdef0123456789abcdef' }), MessageStatus: enumOf(['queued', 'accepted', 'scheduled', 'sending', 'sent', 'delivered', 'read', 'failed', 'undelivered']), SmsStatus: str(), ErrorCode: str({ example: '63016' }), ErrorMessage: str(), AccountSid: str(), From: str(), To: str() }, ['MessageSid']),
  SyncOperation: obj({ client_op_id: str(), kind: enumOf(['task.transition', 'step.result', 'inventory.movement', 'booking.create', 'booking.create_walk_in', 'payment.record', 'quotation.create', 'vehicle.create', 'membership.enrol']), payload: { type: 'object', additionalProperties: true }, device_time: dt() }, ['client_op_id', 'kind', 'payload']),
  SyncResult: obj({ client_op_id: str(), status: enumOf(['applied', 'conflict', 'rejected']), result: { description: 'Operation result, or {error, server_state} for conflict/rejected' } }),
  AuditEvent: obj({ id: uuid(), actor_id: nullable(str()), actor_name: nullable(str()), actor_role: nullable(str()), action: str(), entity_type: str(), entity_id: nullable(str()), outlet_id: nullable(uuid()), before: {}, after: {}, correlation_id: nullable(str()), outcome: str(), created_at: dt() }),
  Kpis: obj({ range: obj({ from: dt(), to: dt() }), period: enumOf(['today', 'week', 'month', 'custom']), revenue_cents: int(), revenue_previous_cents: int(), revenue_trend_pct: nullable(num()), revenue_compare_label: str({ example: 'vs R 12 300 yesterday' }), bookings_today: int(), bookings_count: int({ description: 'Non-cancelled bookings whose slot starts in the range' }), bookings_completed: int(), bookings_in_service: int(), on_time_pct: num(), active_work_orders: int(), completed_today: int(), avg_cycle_minutes: num(), cycle_delta_minutes: num({ description: 'avg_cycle_minutes minus the 7-day average' }), quotes_total: int(), quotes_accepted: int(), exceptions_count: int(), exceptions_breakdown: obj({ blocked: int(), overdue: int(), low_stock: int(), stock_alerts: int({ description: 'Alias of low_stock' }), failed_payments: int() }), bookings_by_hour: arr(obj({ hour: int(), car_wash: int(), auto_body: int(), future: bool() })), revenue_by_outlet: arr(obj({ outlet_id: uuid(), name: str(), revenue_cents: int() })), top_staff: arr(obj({ staff_id: str(), name: str(), initials: str(), points: int(), rank: int(), tier: enumOf(['gold', 'silver', 'bronze']) })), services_count: int(), outlets_count: int(), active_members: int({ description: 'Memberships with status active (platform-wide)' }), membership_mrr_cents: int({ description: 'Σ monthly fee of active memberships' }) }),
  ExceptionItem: obj({ id: str(), kind: enumOf(['blocked', 'overdue', 'low_stock', 'out_of_stock', 'failed_payment']), type: { ...enumOf(['blocked', 'overdue', 'low_stock', 'out_of_stock', 'failed_payment']), description: 'Alias of kind' }, severity: enumOf(['error', 'warning']), priority: enumOf(['high', 'medium', 'low']), title: str(), subtitle: str(), detail: nullable(str()), icon: str(), outlet_id: nullable(uuid()), at: nullable(dt()), created_at: nullable(dt()), link: obj({ type: enumOf(['work_order', 'inventory_item', 'payment', 'booking']), id: str() }) }),
  ActivityItem: obj({ id: uuid(), type: enumOf(['task_event', 'payment_event', 'loyalty', 'inventory_alert']), kind: enumOf(['completed', 'payment', 'quote', 'stock', 'loyalty', 'assigned', 'blocked']), at: dt(), title: str(), subtitle: str(), detail: nullable(str()), icon: str(), tone: enumOf(['success', 'primary', 'warning', 'error', 'neutral']), outlet_id: nullable(uuid()), link: nullable(obj({ type: str(), id: str() })) }),
  StaffPerformanceRow: obj({ staff_id: str(), name: str(), role: str(), outlet_name: nullable(str()), tasks_completed: int(), tasks_verified: int(), avg_cycle_minutes: nullable(num()), checklist_compliance_pct: nullable(num()), points: int({ description: 'Lifetime points' }), points_period: int({ description: 'Points earned in the range' }), rank: int(), delta: int({ description: 'Rank change vs the previous period' }), badges: arr(obj({ code: str(), name: str(), icon: str(), colour: str(), earned_at: dt() })) }),
  AdminTaskEvent: obj({ id: uuid(), task_id: nullable(uuid()), actor_id: nullable(str()), actor_name: nullable(str()), event: str(), from_status: nullable(str()), to_status: nullable(str()), reason: nullable(str()), metadata: nullable({ type: 'object', additionalProperties: true }), created_at: dt() }),
  AdminWorkOrder: obj({ id: uuid(), ref: str(), outlet: obj({ id: uuid(), name: str() }), booking_id: nullable(uuid()), booking_ref: nullable(str()), quotation_id: nullable(uuid()), quotation_ref: nullable(str()), customer_id: str(), customer_name: str(), vehicle: obj({ id: uuid(), registration_no: str(), make: nullable(str()), model: nullable(str()) }), service: obj({ id: uuid(), name: str(), category: str() }), status: enumOf(workStatus), priority: int({ minimum: 1, maximum: 3 }), bay: nullable(str()), assignee_id: nullable(str()), assignee_name: nullable(str()), eta_at: nullable(dt()), due_at: nullable(dt()), started_at: nullable(dt()), completed_at: nullable(dt()), verified_at: nullable(dt()), blocked_reason: nullable(str()), steps_done: int(), step_count: int(), progress_pct: int(), task_id: nullable(uuid({ description: 'First task — the id /tasks/{id}/assign and /transition act on' })), task_status: nullable(enumOf(workStatus)), events: arr(ref('AdminTaskEvent')), created_at: dt(), updated_at: dt() }),
  AdminCustomer: { allOf: [ref('Profile'), obj({ vehicle_count: int(), booking_count: int(), loyalty: nullable(obj({ customer_id: str(), tier: enumOf(tiers), balance_points: int(), lifetime_points: int(), tier_since: nullable(dt()), plan_code: nullable(str()), plan_name: nullable(str()), membership_status: nullable(enumOf(membershipStatus)), included_remaining: int() })) })] },
  ChecklistTemplate: obj({ id: uuid(), name: str(), category: enumOf(['car_wash', 'auto_body']), version: int(), status: enumOf(['draft', 'published', 'archived']), steps: arr(ref('ChecklistStep')), outlet_id: nullable(uuid()), created_by: nullable(str()), created_at: dt() }),
  FeatureFlag: obj({ key: str(), enabled: bool(), description: nullable(str()), updated_at: dt() }),
  OutletService: obj({ outlet_id: uuid(), service_id: uuid(), price_cents: nullable(int({ description: 'Legacy single price (null = inherit)' })), is_available: bool(), display_name: nullable(str()), price_small_cents: nullable(int()), price_large_cents: nullable(int()), price_general_cents: nullable(int()), pricing_mode: nullable(enumOf(pricingModes)), vat_mode: nullable(enumOf(vatModes)), sort_order: nullable(int()) }, ['outlet_id', 'service_id', 'price_cents', 'is_available']),
  AdminPayment: obj({ id: uuid(), booking_id: nullable(uuid()), booking_ref: nullable(str({ example: 'SPK-2026-0091' })), outlet_id: nullable(uuid()), outlet_name: nullable(str()), customer_id: str(), customer_name: str(), provider: str(), method_brand: nullable(str({ example: 'visa' })), method_last4: nullable(str({ example: '4242' })), amount_cents: int(), currency: str(), status: enumOf(paymentStatus), receipt_no: nullable(str({ example: 'RCP-70001' })), failure_reason: nullable(str()), verified_at: nullable(dt()), created_at: dt() }, ['id', 'customer_id', 'customer_name', 'provider', 'amount_cents', 'currency', 'status', 'created_at']),
  ReportSummary: obj({
    range: obj({ from: dt(), to: dt(), outlet_ids: nullable(arr(uuid())) }),
    financial: obj({ revenue_cents: int({ description: 'Sum of successful payments created in range' }), refunds_cents: int(), payments_total: int(), payments_successful: int(), payments_failed: int(), avg_ticket_cents: int(), by_status: arr(obj({ status: enumOf(paymentStatus), count: int(), amount_cents: int() })), by_outlet: arr(obj({ outlet_id: uuid(), name: str(), revenue_cents: int(), bookings: int() })), by_service: arr(obj({ service_id: uuid(), name: str(), category: str(), revenue_cents: int(), count: int() })) }),
    operational: obj({ bookings: int(), created: int(), pending: int(), confirmed: int(), in_service: int(), completed: int(), cancelled: int(), work_orders_completed: int(), on_time_pct: num(), avg_cycle_minutes: num(), checklist_compliance_pct: num(), quotes: obj({ requested: int(), quoted: int(), accepted: int(), declined: int(), expired: int(), converted: int() }) }),
    loyalty: obj({ points_issued: int(), points_redeemed: int(), points_expired: int(), ledger_entries: int(), outlet_scoped: bool() }),
    inventory: obj({ items_active: int(), items_below_threshold: int(), items_out_of_stock: int(), open_alerts: int() }),
    notifications: obj({ total: int(), delivered: int(), failed: int(), suppressed: int(), delivery_rate_pct: num({ description: 'delivered / (total − suppressed)' }), outlet_scoped: bool() }),
  }, ['range', 'financial', 'operational', 'loyalty', 'inventory', 'notifications']),
  IntegrationCard: { type: 'object', properties: { key: enumOf(['supabase', 'firebase', 'payments', 'whatsapp']), name: str(), status: enumOf(['connected', 'sandbox', 'disabled', 'error']), detail: str(), icon: str() }, required: ['key', 'name', 'status', 'detail', 'icon'], additionalProperties: true, description: 'Per-key extras: supabase {ok, latency_ms, url}; firebase {project_id, emulator}; payments {provider, sandbox, sandbox_confirm_enabled}; whatsapp {enabled, provider: twilio|sandbox, configured, messaging_service (masked MG… SID), status_callback}' },
  LeaderboardRow: obj({ staff_id: str(), name: str(), points: int(), rank: int(), delta: int({ description: 'Rank change vs previous period (+ = moved up)' }) }),
  // Membership plans (docs/MEMBERSHIPS.md)
  MembershipEntitlement: obj({ id: uuid(), code: str({ example: 'G1' }), label: str({ example: '4 × Sparkling Wash' }), quantity: int(), period: enumOf(['month', 'year']), sort_order: int(), services: arr(obj({ id: uuid(), code: str({ example: 'SPARKLING_WASH' }), name: str(), is_primary: bool() })) }, ['id', 'code', 'label', 'quantity', 'period', 'services']),
  MembershipGroup: obj({ id: uuid(), code: str({ example: 'washes' }), name: str(), selection: enumOf(['choose_one', 'all']), sort_order: int(), entitlements: arr(ref('MembershipEntitlement')) }, ['id', 'code', 'name', 'selection', 'entitlements']),
  MembershipPlan: obj({ id: uuid(), code: str({ example: 'gold' }), tier: enumOf(tiers), name: str(), tagline: nullable(str()), monthly_fee_cents: int({ example: 29500 }), discount_pct: num({ example: 10 }), discount_scope: enumOf(discountScopes), discount_note: nullable(str()), color: nullable(str()), sort_order: int(), is_active: bool(), groups: arr(ref('MembershipGroup')) }, ['id', 'code', 'tier', 'name', 'monthly_fee_cents', 'discount_pct', 'discount_scope', 'groups']),
  AdminMembershipPlan: { allOf: [ref('MembershipPlan'), obj({ member_count: int({ description: 'active + past_due' }), mrr_cents: int({ description: 'Σ fee of active members' }) }, ['member_count', 'mrr_cents'])] },
  MembershipPlanInput: obj({ name: str(), tagline: nullable(str()), monthly_fee_cents: int({ minimum: 1 }), discount_pct: num({ minimum: 0, maximum: 100 }), discount_scope: enumOf(discountScopes), discount_note: nullable(str()), color: nullable(str()), sort_order: int(), is_active: bool(), groups: arr(obj({ code: str(), name: str(), selection: enumOf(['choose_one', 'all']), sort_order: int(), entitlements: arr(obj({ code: str(), label: str(), quantity: int({ minimum: 1 }), period: enumOf(['month', 'year']), sort_order: int(), service_codes: arr(str()) }, ['code', 'label', 'quantity', 'service_codes'])) }, ['code', 'name', 'entitlements'])) }, ['name', 'monthly_fee_cents', 'discount_pct', 'discount_scope', 'groups']),
  Membership: obj({ id: uuid(), ref: str({ example: 'MEM-2026-0001' }), customer_id: str(), plan_id: uuid(), status: enumOf(membershipStatus), started_at: nullable(dt()), current_period_start: nullable(dt()), current_period_end: nullable(dt()), cancel_at_period_end: bool(), cancelled_at: nullable(dt()), ended_at: nullable(dt()), next_plan_id: nullable(uuid({ description: 'Plan applied at the next paid invoice (downgrade at renewal / upgrade on payment)' })), payment_method: enumOf(['card', 'cash', 'eft', 'sandbox']), client_op_id: nullable(str()), created_by: nullable(str()), created_at: dt(), updated_at: dt() }, ['id', 'ref', 'customer_id', 'plan_id', 'status', 'cancel_at_period_end', 'payment_method']),
  MembershipInvoice: obj({ id: uuid(), ref: str({ example: 'MINV-2026-0101' }), membership_id: uuid(), customer_id: str(), period_start: dt(), period_end: dt(), amount_cents: int(), status: enumOf(['pending', 'paid', 'failed', 'void']), due_at: dt(), paid_at: nullable(dt()), payment_id: nullable(uuid()), idempotency_key: str({ example: 'renewal:<membership_id>:2026-10-10' }), created_at: dt(), updated_at: dt() }, ['id', 'ref', 'membership_id', 'period_start', 'period_end', 'amount_cents', 'status', 'due_at']),
  Allowance: obj({ entitlement_id: uuid(), entitlement_code: str({ example: 'G1' }), group_code: str({ example: 'washes' }), label: str(), quantity: int(), used: int(), remaining: int(), period: enumOf(['month', 'year']), period_start: dt(), period_end: dt() }, ['entitlement_id', 'entitlement_code', 'group_code', 'label', 'quantity', 'used', 'remaining', 'period', 'period_start', 'period_end']),
  MembershipBrief: obj({ membership_id: uuid(), plan_code: str(), plan_name: str(), tier: enumOf(tiers), status: enumOf(membershipStatus), period_end: nullable(dt()), cancel_at_period_end: bool(), allowances: arr(ref('Allowance')) }, ['membership_id', 'plan_code', 'plan_name', 'tier', 'status', 'allowances']),
  MembershipSummary: obj({ membership: nullable(ref('Membership')), plan: nullable(ref('MembershipPlan')), next_plan: nullable(obj({ id: uuid(), code: str(), name: str(), monthly_fee_cents: int() })), selections: { type: 'object', additionalProperties: str(), description: '{ [group_code]: entitlement_code }' }, allowances: arr(ref('Allowance')), open_invoice: nullable(ref('MembershipInvoice')), invoices: { ...arr(ref('MembershipInvoice')), description: 'Last 12, newest first' }, next_renewal_at: nullable(dt()), benefits_summary: str({ example: '3 of 4 Sparkling Washes left · 10% discount on any other Sparkling service' }) }, ['membership', 'plan', 'selections', 'allowances', 'open_invoice', 'invoices', 'next_renewal_at', 'benefits_summary']),
  MembershipPayment: { allOf: [ref('Payment'), obj({ client_secret: nullable(str({ description: 'Sandbox intent secret (null on replay)' })) })] },
  MembershipSubscribe: obj({ plan_code: str({ example: 'gold' }), selections: { type: 'object', additionalProperties: str(), example: { washes: 'G1' } }, payment_method: enumOf(['card']), client_op_id: str() }, ['plan_code', 'client_op_id']),
  MembershipSubscribed: obj({ membership: ref('Membership'), invoice: ref('MembershipInvoice'), payment: nullable(ref('MembershipPayment')), duplicate: bool() }, ['membership', 'invoice', 'payment', 'duplicate']),
  MembershipEnrol: obj({ plan_code: str(), selections: { type: 'object', additionalProperties: str() }, payment_method: enumOf(['cash', 'card_terminal', 'eft']), reference: nullable(str()), outlet_id: uuid(), client_op_id: str() }, ['plan_code', 'payment_method', 'client_op_id']),
  MembershipEnrolled: obj({ membership: ref('Membership'), invoice: ref('MembershipInvoice'), payment: nullable(ref('Payment')), duplicate: bool(), summary: ref('MembershipSummary') }, ['membership', 'invoice', 'payment', 'duplicate', 'summary']),
  MembershipRecordPayment: obj({ method: enumOf(['cash', 'card_terminal', 'eft']), reference: nullable(str()), outlet_id: uuid(), client_op_id: str() }, ['method', 'client_op_id']),
  MembershipPaymentRecorded: obj({ payment: ref('Payment'), invoice: ref('MembershipInvoice'), membership: ref('Membership'), duplicate: bool() }, ['payment', 'invoice', 'membership', 'duplicate']),
  MembershipChangePlan: obj({ membership: ref('Membership'), change: enumOf(['upgrade', 'downgrade']), invoice: nullable(ref('MembershipInvoice')), payment: nullable(ref('MembershipPayment')), applies_at: nullable(dt({ description: 'Downgrade: current period end' })) }, ['membership', 'change', 'invoice', 'payment', 'applies_at']),
  MemberRow: obj({ membership: ref('Membership'), customer: nullable(obj({ id: str(), full_name: str(), phone: nullable(str()), email: nullable(str()) })), plan: obj({ id: uuid(), code: str(), name: str(), tier: enumOf(tiers), monthly_fee_cents: int() }), next_plan: nullable(obj({ id: uuid(), code: str(), name: str() })), selections: { type: 'object', additionalProperties: str(), description: '{ [group_code]: entitlement_code }' }, allowances: arr(ref('Allowance')), used: int({ description: 'Monthly washes used this period' }), remaining: int({ description: 'Monthly washes left this period' }), open_invoice: nullable(ref('MembershipInvoice')) }, ['membership', 'customer', 'plan', 'selections', 'allowances', 'used', 'remaining', 'open_invoice']),
  RenewalRun: obj({ ran_at: dt(), scanned: int(), rolled: int(), cancelled: int(), expired: int(), invoices_created: int(), auto_charged: int(), past_due: int(), errors: arr(obj({ membership_id: uuid(), message: str() })) }),
};

const paths = {};
const add = (path, method, op) => {
  paths[path] ??= {};
  paths[path][method] = { responses: { ...common }, ...op, responses: { ...(op.responses ?? {}), ...common, ...(op.responses ?? {}) } };
  if (!paths[path][method].responses['200'] && !paths[path][method].responses['201'] && !paths[path][method].responses['204']) throw new Error(`no success response for ${method} ${path}`);
};
const T = { auth: 'Auth & profile', cat: 'Catalogue', veh: 'Vehicles', bk: 'Bookings', qt: 'Quotations', pay: 'Payments', loy: 'Loyalty', mem: 'Memberships', staff: 'Staff', inv: 'Inventory', adm: 'Admin', not: 'Notifications', pub: 'Public quote page', sys: 'System' };

add('/config', 'get', { tags: [T.sys], operationId: 'getConfig', summary: 'Public-safe feature flags (no auth)', security: [], responses: { 200: json(obj({ flags: obj({ cash_on_collection: bool(), payments_sandbox: bool(), whatsapp_enabled: bool() }) })) } });
add('/health', 'get', { tags: [T.sys], operationId: 'getHealth', summary: 'Liveness probe', security: [], responses: { 200: json(obj({ ok: bool(), version: str(), service: str(), time: dt() })) } });

// Auth
add('/auth/session', 'post', { tags: [T.auth], operationId: 'postAuthSession', summary: 'Upsert profile, claim seeded profile by e-mail, set custom claims', requestBody: body(obj({ app: enumOf(['customer', 'staff', 'admin']), full_name: str(), phone: str() }, ['app'])), responses: { 200: json(obj({ profile: ref('Profile'), outlet_ids: arr(uuid()), claims_updated: bool() })) } });
add('/me', 'get', { tags: [T.auth], operationId: 'getMe', summary: 'Current profile, outlets, loyalty account and membership summary', responses: { 200: json(obj({ profile: ref('Profile'), outlets: arr(ref('Outlet')), loyalty_account: nullable(ref('LoyaltyAccount')), membership: nullable(ref('MembershipBrief')) })) } });
add('/me', 'patch', { tags: [T.auth], operationId: 'patchMe', summary: 'Update editable profile fields', requestBody: body(obj({ full_name: str(), phone: nullable(str()), avatar_url: nullable(str()), marketing_opt_in: bool(), whatsapp_opt_in: bool(), push_opt_in: bool(), locale: str(), reduced_motion: bool(), haptics: bool() })), responses: { 200: json(obj({ profile: ref('Profile') })) } });
add('/devices', 'post', { tags: [T.auth], operationId: 'postDevice', summary: 'Register an FCM device token', requestBody: body(obj({ token: str(), platform: enumOf(['android', 'ios', 'web']), app: enumOf(['customer', 'staff', 'admin']) }, ['token', 'platform', 'app'])), responses: { 201: json(obj({ device: { type: 'object', additionalProperties: true } }), 'Registered') } });
add('/devices/{token}', 'delete', { tags: [T.auth], operationId: 'deleteDevice', summary: 'Remove a device token', parameters: [p('token', str())], responses: { 204: { description: 'Removed' } } });

// Catalogue
add('/outlets', 'get', { tags: [T.cat], operationId: 'listOutlets', summary: 'Active outlets (optionally sorted by distance)', parameters: [q('lat', num()), q('lng', num())], responses: { 200: json(obj({ data: arr(ref('Outlet')) })) } });
add('/outlets/{id}/services', 'get', { tags: [T.cat], operationId: 'listOutletServices', summary: 'Offers at an outlet: per-size prices, composition, add-ons, grouped (with ?vehicle_size: price_cents/total resolved for that size and the caller’s membership — covered services come back at R0 with "Included in Gold · 3 of 4 left")', parameters: [p('id'), q('vehicle_size', enumOf(vehicleSizes))], responses: { 200: json(obj({ data: arr({ allOf: [ref('OutletServiceOffer'), obj({ membership: nullable(obj({ membership_id: uuid(), plan_code: str(), plan_name: str(), benefit: nullable(enumOf(['included', 'discount'])), entitlement_id: nullable(uuid()), entitlement_code: nullable(str()), remaining_after: nullable(int()), period_end: nullable(dt()) })) })] }), groups: arr(enumOf(serviceGroups)), tier: enumOf(tiers), vehicle_size: nullable(enumOf(vehicleSizes)), membership: nullable(obj({ plan_code: str(), plan_name: str(), status: enumOf(membershipStatus) })) }, ['data', 'groups', 'tier'])) } });
add('/availability', 'get', { tags: [T.cat], operationId: 'getAvailability', summary: 'Bookable slots for a service at an outlet on a date', parameters: [q('outlet_id', uuid(), true), q('service_id', uuid(), true), q('date', date(), true)], responses: { 200: json(obj({ data: arr(ref('Slot')), outlet_id: uuid(), service_id: uuid(), date: date() })) } });

// Vehicles
add('/vehicles', 'get', { tags: [T.veh], operationId: 'listVehicles', summary: 'Own vehicles (customer) or search (staff)', parameters: [q('customer_id', str()), q('registration_no', str())], responses: { 200: json(obj({ data: arr(ref('Vehicle')) })) } });
add('/vehicles', 'post', { tags: [T.veh], operationId: 'createVehicle', summary: 'Add a vehicle (409 with existing_vehicle_id on duplicate unless force)', requestBody: body(ref('VehicleCreate')), responses: { 201: json(obj({ vehicle: ref('Vehicle') }), 'Created'), 200: json(obj({ vehicle: ref('Vehicle') }), 'Duplicate replay / forced merge') } });
add('/vehicles/{id}', 'patch', { tags: [T.veh], operationId: 'updateVehicle', summary: 'Update own vehicle', parameters: [p('id')], requestBody: body(ref('VehicleCreate')), responses: { 200: json(obj({ vehicle: ref('Vehicle') })) } });
add('/vehicles/{id}', 'delete', { tags: [T.veh], operationId: 'deleteVehicle', summary: 'Soft-delete own vehicle', parameters: [p('id')], responses: { 204: { description: 'Deactivated' } } });
add('/vehicles/parse-disc', 'post', { tags: [T.veh], operationId: 'parseDisc', summary: 'Server-side parse of an SA licence-disc PDF417 payload', requestBody: body(obj({ raw: str() }, ['raw'])), responses: { 200: json(obj({ vehicle: ref('ParsedDisc') })) } });

// Bookings
add('/bookings', 'get', { tags: [T.bk], operationId: 'listBookings', summary: 'Own bookings (customer) or outlet bookings (staff)', parameters: [...pageParams, q('status', str({ description: 'Comma-separated statuses' })), q('outlet_id', uuid()), q('customer_id', str()), q('from', dt()), q('to', dt())], responses: { 200: json(paged(ref('Booking'))) } });
add('/bookings', 'post', { tags: [T.bk], operationId: 'createBooking', summary: 'Create a booking (server-side pricing, slot validated). Staff: customer_id + walk_in (slot defaults to the next grid slot, starts confirmed, optional checkin)', requestBody: body(ref('BookingCreate')), responses: { 201: json(ref('BookingCreated'), 'Created (work_order/task present when checkin was requested)'), 200: json(ref('BookingCreated'), 'Replay of the same client_op_id') } });
add('/bookings/{id}', 'get', { tags: [T.bk], operationId: 'getBooking', summary: 'Booking with payment and timeline', parameters: [p('id')], responses: { 200: json(ref('BookingDetail')) } });
add('/bookings/{id}/cancel', 'post', { tags: [T.bk], operationId: 'cancelBooking', summary: 'Cancel (allowed until in_service)', parameters: [p('id')], requestBody: body(obj({ reason: nullable(str()) }), false), responses: { 200: json(obj({ booking: ref('Booking') })) } });
add('/bookings/{id}/reschedule', 'post', { tags: [T.bk], operationId: 'rescheduleBooking', summary: 'Move to another available slot', parameters: [p('id')], requestBody: body(obj({ slot_start: dt() }, ['slot_start'])), responses: { 200: json(obj({ booking: ref('Booking') })) } });
add('/bookings/{id}/checkin', 'post', { tags: [T.bk], operationId: 'checkInBooking', summary: 'Staff check-in: creates work order + task, status in_service', parameters: [p('id')], requestBody: body(obj({ bay: nullable(str()), priority: int({ minimum: 1, maximum: 3 }) }), false), responses: { 201: json(obj({ booking: ref('Booking'), work_order: ref('WorkOrder'), task: ref('Task'), created: bool() }), 'Work order created'), 200: json(obj({ booking: ref('Booking'), work_order: ref('WorkOrder'), task: ref('Task'), created: bool() }), 'Already checked in') } });

// Quotations
add('/quotations', 'get', { tags: [T.qt], operationId: 'listQuotations', summary: 'Own (customer) or outlet (staff) quotations', parameters: [...pageParams, q('status', str()), q('outlet_id', uuid())], responses: { 200: json(paged(ref('Quotation'))) } });
add('/quotations', 'post', { tags: [T.qt], operationId: 'createQuotation', summary: 'Customer: request a repair quotation (status requested). Staff: raise a quote for a walk-in customer in one step (status quoted, amount = Σ items, public token valid 30 days, quote_ready sent unless send_to_customer:false; audited quotation.raise)', requestBody: body({ anyOf: [ref('QuotationRequest'), ref('QuotationRaise')], description: 'Customer request or staff raise (the branch is chosen by the caller’s role)' }), responses: { 201: json(obj({ quotation: ref('Quotation'), duplicate: bool(), notification: arr(ref('NotifyOutcome')) }), 'Created'), 200: json(obj({ quotation: ref('Quotation'), duplicate: bool() }), 'Replay of the same client_op_id') } });
add('/quotations/{id}', 'get', { tags: [T.qt], operationId: 'getQuotation', summary: 'Quotation with items, attachments (API-served urls), decision provenance, pdf_url and (staff) public_url', parameters: [p('id')], responses: { 200: json({ allOf: [ref('Quotation'), obj({ work_order: nullable(obj({ id: uuid(), ref: str(), status: str() })) })] }) } });
add('/quotations/{id}/photos', 'post', { tags: [T.qt], operationId: 'addQuotationPhoto', summary: 'Upload a damage photo (multipart field photo; jpeg/png/heic/webp sniffed by magic bytes, ≤ 10 MB, ≤ 10 per quotation, before the decision) — stored in Cloud Storage quotations/<quotation_id>/<attachment_id>.<ext>', parameters: [p('id')], requestBody: { required: true, content: { 'multipart/form-data': { schema: obj({ photo: str({ format: 'binary' }), caption: str({ maxLength: 200 }) }, ['photo']), encoding: { photo: { contentType: 'image/jpeg, image/png, image/heic, image/webp' } } } } }, responses: { 201: json(obj({ attachment: ref('QuotationAttachment') }), 'Stored') } });
add('/quotations/{id}/photos/{attachmentId}', 'get', { tags: [T.qt], operationId: 'getQuotationPhoto', summary: 'Stream a damage photo (owner / outlet staff; Cache-Control: private, max-age=3600)', parameters: [p('id'), p('attachmentId')], responses: { 200: { description: 'Image bytes', content: { 'image/jpeg': { schema: str({ format: 'binary' }) }, 'image/png': { schema: str({ format: 'binary' }) }, 'image/heic': { schema: str({ format: 'binary' }) }, 'image/webp': { schema: str({ format: 'binary' }) } } } } });
add('/quotations/{id}/photos/{attachmentId}', 'delete', { tags: [T.qt], operationId: 'deleteQuotationPhoto', summary: 'Staff: remove the object and the attachment row (before the decision; audited quotation.photo_delete)', parameters: [p('id'), p('attachmentId')], responses: { 204: { description: 'Removed' } } });
add('/quotations/{id}/share', 'post', { tags: [T.qt], operationId: 'shareQuotation', summary: 'Staff: rotate the public token (+30 days) and re-send quote_ready (push + WhatsApp); 1/min per quotation (429); audited quotation.share', parameters: [p('id')], responses: { 200: json(obj({ public_url: nullable(str()), expires_at: dt(), notification: arr(ref('NotifyOutcome')), quotation: ref('Quotation') })) } });
add('/quotations/{id}/pdf', 'get', { tags: [T.qt], operationId: 'getQuotationPdf', summary: 'A4 PDF of the quotation (header, outlet, customer, vehicle, items, total, validity, status/decision, photo thumbnails, ref + QR of the public link); Content-Disposition: attachment; filename="<ref>.pdf"', parameters: [p('id')], responses: { 200: { description: 'PDF', content: { 'application/pdf': { schema: str({ format: 'binary' }) } } } } });
add('/quotations/{id}/attachments', 'post', { tags: [T.qt], operationId: 'addQuotationAttachment', summary: 'Register an uploaded Cloud Storage object', parameters: [p('id')], requestBody: body(obj({ storage_path: str(), mime_type: str(), size_bytes: int(), sha256: nullable(str()) }, ['storage_path', 'mime_type', 'size_bytes'])), responses: { 201: json(obj({ attachment: ref('Attachment') }), 'Created') } });
add('/quotations/{id}/quote', 'post', { tags: [T.qt], operationId: 'quoteQuotation', summary: 'Supervisor/manager issues the quote (notifies customer)', parameters: [p('id')], requestBody: body(obj({ amount_cents: int(), line_items: arr(ref('LineItem')), valid_until: date(), items_note: nullable(str()) }, ['amount_cents', 'valid_until'])), responses: { 200: json(obj({ quotation: ref('Quotation') })) } });
add('/quotations/{id}/decision', 'post', { tags: [T.qt], operationId: 'decideQuotation', summary: 'Customer accepts or declines in the app (decision_source app). One-time: any later decision — in-app or via the public link — is 409 conflict {decided_at, status}; accepting after valid_until is 410 gone', parameters: [p('id')], requestBody: body(obj({ decision: enumOf(['accept', 'decline']), note: nullable(str()) }, ['decision'])), responses: { 200: json(obj({ quotation: ref('Quotation') })) } });
add('/quotations/{id}/convert', 'post', { tags: [T.qt], operationId: 'convertQuotation', summary: 'accepted → converted; creates work order + task', parameters: [p('id')], responses: { 201: json(obj({ quotation: ref('Quotation'), work_order: ref('WorkOrder'), task: ref('Task') }), 'Converted') } });

// Public quote page (no auth; token-scoped; 60/min per IP + token)
const tokenP = p('token', str({ format: 'uuid', description: 'Public link token from ${PUBLIC_WEB_BASE_URL}/q/<token>' }));
add('/public/quotations/{token}', 'get', { tags: [T.pub], operationId: 'getPublicQuotation', summary: 'Public quotation view for the link holder (first name only, no phone / e-mail). 404 unknown token, 410 gone {ref,status} once the link expired', security: [], parameters: [tokenP], responses: { 200: json(ref('PublicQuotation')) } });
add('/public/quotations/{token}/photos/{attachmentId}', 'get', { tags: [T.pub], operationId: 'getPublicQuotationPhoto', summary: 'Stream a damage photo through the public link', security: [], parameters: [tokenP, p('attachmentId')], responses: { 200: { description: 'Image bytes', content: { 'image/jpeg': { schema: str({ format: 'binary' }) }, 'image/png': { schema: str({ format: 'binary' }) }, 'image/heic': { schema: str({ format: 'binary' }) }, 'image/webp': { schema: str({ format: 'binary' }) } } } } });
add('/public/quotations/{token}/pdf', 'get', { tags: [T.pub], operationId: 'getPublicQuotationPdf', summary: 'Same PDF as GET /quotations/{id}/pdf, through the public link', security: [], parameters: [tokenP], responses: { 200: { description: 'PDF', content: { 'application/pdf': { schema: str({ format: 'binary' }) } } } } });
add('/public/quotations/{token}/decision', 'post', { tags: [T.pub], operationId: 'decidePublicQuotation', summary: 'Accept or decline via the link (decision_source public_link, decision_by_name; audited quotation.decision_public with IP + user agent; quote_decided push to the assessor + outlet supervisors/managers, quote_decision_receipt to the customer). One-time: 409 conflict when already decided (in-app or via link), 410 gone when expired', security: [], parameters: [tokenP], requestBody: body(ref('PublicDecision')), responses: { 200: json(ref('PublicQuotation'), 'Decided — returns the public view') } });

// Payments
add('/payments/methods', 'get', { tags: [T.pay], operationId: 'listPaymentMethods', summary: 'Tokenised payment methods', responses: { 200: json(obj({ data: arr(ref('PaymentMethod')) })) } });
add('/payments/methods', 'post', { tags: [T.pay], operationId: 'addPaymentMethod', summary: 'Store a provider token (never a PAN)', requestBody: body(obj({ provider_token: str(), brand: str(), last4: nullable(str()), label: str(), is_default: bool() }, ['provider_token', 'brand'])), responses: { 201: json(obj({ method: ref('PaymentMethod') }), 'Created') } });
add('/payments/intents', 'post', { tags: [T.pay], operationId: 'createPaymentIntent', summary: 'Create a payment intent for a booking', requestBody: body(obj({ booking_id: uuid(), method_id: nullable(uuid()), idempotency_key: str() }, ['booking_id', 'idempotency_key'])), responses: { 201: json(obj({ payment: ref('Payment'), client_secret: nullable(str()), redirect_url: nullable(str()) }), 'Created'), 200: json(obj({ payment: ref('Payment'), client_secret: nullable(str()), redirect_url: nullable(str()), duplicate: bool() }), 'Replay') } });
add('/payments/{id}/sandbox-confirm', 'post', { tags: [T.pay], operationId: 'sandboxConfirmPayment', summary: 'Simulate a signed provider webhook (flag payments_sandbox)', parameters: [p('id')], requestBody: body(obj({ outcome: enumOf(['succeeded', 'failed']) }), false), responses: { 200: json(obj({ payment: ref('Payment'), duplicate: bool() })) } });
add('/payments/record', 'post', { tags: [T.pay], operationId: 'recordPosPayment', summary: 'Staff: attest an in-person (cash / card terminal) payment for a booking at their outlet — provider pos, successful, receipt from next_receipt_no(), payment_events pos.recorded, audited', requestBody: body(ref('PosPaymentRecord')), responses: { 201: json(obj({ payment: ref('Payment'), duplicate: bool() }), 'Recorded'), 200: json(obj({ payment: ref('Payment'), duplicate: bool() }), 'Replay of the same idempotency_key') } });
add('/payments/webhook', 'post', { tags: [T.pay], operationId: 'paymentWebhook', summary: 'Provider webhook (HMAC-SHA256 in X-Signature; idempotent by event id)', security: [], parameters: [{ name: 'X-Signature', in: 'header', required: true, schema: str() }], requestBody: body(ref('ProviderEvent')), responses: { 200: json(obj({ received: bool(), duplicate: bool(), payment_id: uuid(), status: enumOf(paymentStatus), ignored: nullable(str()) })) } });
add('/payments/{id}', 'get', { tags: [T.pay], operationId: 'getPayment', summary: 'Payment with receipt', parameters: [p('id')], responses: { 200: json(obj({ payment: { allOf: [ref('Payment'), obj({ receipt: nullable(obj({ receipt_no: str(), amount_cents: int(), currency: str(), paid_at: nullable(dt()), provider: str(), provider_ref: nullable(str()) })) })] } })) } });

// Loyalty
add('/loyalty/account', 'get', { tags: [T.loy], operationId: 'getLoyaltyAccount', summary: 'Account, tier config (tier = membership plan; next_tier is informational only) and membership summary', responses: { 200: json(obj({ account: ref('LoyaltyAccount'), tier_config: nullable(ref('LoyaltyTier')), tiers: arr(ref('LoyaltyTier')), next_tier: nullable(obj({ tier: enumOf(tiers), name: str(), points_needed: int() })), published_version: nullable(int()), rules: nullable(ref('LoyaltyRules')), membership: nullable(ref('MembershipBrief')) })) } });
add('/loyalty/rewards', 'get', { tags: [T.loy], operationId: 'listRewards', summary: 'Rewards with eligibility by tier', responses: { 200: json(obj({ data: arr(ref('Reward')), balance_points: int(), tier: enumOf(tiers) })) } });

// Memberships (docs/MEMBERSHIPS.md)
add('/memberships/plans', 'get', { tags: [T.mem], operationId: 'listMembershipPlans', summary: 'Active plans with groups → entitlements → services, plus the caller’s current plan', responses: { 200: json(obj({ data: arr(ref('MembershipPlan')), current_plan_code: nullable(str()), current_status: nullable(enumOf(membershipStatus)) }, ['data', 'current_plan_code'])) } });
add('/memberships/me', 'get', { tags: [T.mem], operationId: 'getMyMembership', summary: 'Live membership, plan, selections, allowances (remaining per entitlement in its current period), open/last invoices', responses: { 200: json(ref('MembershipSummary')) } });
add('/memberships', 'post', { tags: [T.mem], operationId: 'subscribeMembership', summary: 'Subscribe: pending membership + first invoice + sandbox payment intent. Paying it (sandbox-confirm / provider webhook) activates the membership (period = now → +1 month, tier = plan, membership_activated). 409 conflict when a live membership exists', requestBody: body(ref('MembershipSubscribe')), responses: { 201: json(ref('MembershipSubscribed'), 'Created (status pending)'), 200: json(ref('MembershipSubscribed'), 'Replay of the same client_op_id') } });
add('/memberships/me/invoices/{id}/pay', 'post', { tags: [T.mem], operationId: 'payMembershipInvoice', summary: 'Sandbox payment intent for a pending renewal/upgrade invoice (a still-open intent is replayed); success rolls the period (membership_renewed)', parameters: [p('id')], responses: { 201: json(obj({ invoice: ref('MembershipInvoice'), payment: ref('MembershipPayment'), duplicate: bool() }), 'Intent created'), 200: json(obj({ invoice: ref('MembershipInvoice'), payment: ref('MembershipPayment'), duplicate: bool() }), 'Open intent replayed') } });
add('/memberships/me/selections', 'put', { tags: [T.mem], operationId: 'changeMembershipSelections', summary: 'Change the chosen option per choose_one group; 409 once any allowance was used this period', requestBody: body(obj({ selections: { type: 'object', additionalProperties: str() } }, ['selections'])), responses: { 200: json(ref('MembershipSummary')) } });
add('/memberships/me/change-plan', 'post', { tags: [T.mem], operationId: 'changeMembershipPlan', summary: 'Upgrade (higher fee): full-fee invoice + intent now, plan and a fresh period start on payment. Downgrade: next_plan_id applied at renewal. 409 when already on the plan or not active', requestBody: body(obj({ plan_code: str(), selections: { type: 'object', additionalProperties: str() } }, ['plan_code'])), responses: { 201: json(ref('MembershipChangePlan'), 'Upgrade invoice created'), 200: json(ref('MembershipChangePlan'), 'Downgrade scheduled') } });
add('/memberships/me/cancel', 'post', { tags: [T.mem], operationId: 'cancelMembership', summary: 'Cancel at period end (default; benefits continue until then) or immediately (cancelled, tier → silver, pending invoices void). membership_cancelled', requestBody: body(obj({ at_period_end: { type: 'boolean', default: true }, reason: nullable(str()) }), false), responses: { 200: json(obj({ membership: ref('Membership') })) } });
add('/staff/customers/{id}/membership', 'get', { tags: [T.mem], operationId: 'getStaffCustomerMembership', summary: 'Staff: a customer’s membership summary (same shape as /memberships/me)', parameters: [p('id', str())], responses: { 200: json(ref('MembershipSummary')) } });
add('/staff/customers/{id}/membership', 'post', { tags: [T.mem], operationId: 'enrolStaffCustomerMembership', summary: 'Staff: enrol at the counter — membership active immediately, invoice paid, payment row provider pos (method, recorded_by, receipt), membership_activated; audited membership.enrol. Also sync-batch kind membership.enrol', parameters: [p('id', str())], requestBody: body(ref('MembershipEnrol')), responses: { 201: json(ref('MembershipEnrolled'), 'Enrolled'), 200: json(ref('MembershipEnrolled'), 'Replay of the same client_op_id') } });
add('/staff/memberships/{id}/invoices/{invoiceId}/record-payment', 'post', { tags: [T.mem], operationId: 'recordMembershipInvoicePayment', summary: 'Staff: pay a pending renewal at the counter (pos payment row; rolls the period, membership_renewed); 409 when the invoice is not pending', parameters: [p('id'), p('invoiceId')], requestBody: body(ref('MembershipRecordPayment')), responses: { 201: json(ref('MembershipPaymentRecorded'), 'Recorded'), 200: json(ref('MembershipPaymentRecorded'), 'Replay') } });
add('/loyalty/ledger', 'get', { tags: [T.loy], operationId: 'getLoyaltyLedger', summary: 'Ledger entries', parameters: pageParams, responses: { 200: json(paged(ref('LedgerEntry'))) } });
add('/loyalty/rewards/{id}/redeem', 'post', { tags: [T.loy], operationId: 'redeemReward', summary: 'Redeem (idempotent by Idempotency-Key)', parameters: [p('id'), { name: 'Idempotency-Key', in: 'header', required: true, schema: str() }], responses: { 201: json(ref('Redemption'), 'Redeemed (or replayed)') } });

// Staff
add('/tasks', 'get', { tags: [T.staff], operationId: 'listTasks', summary: 'Tasks by scope', parameters: [q('scope', enumOf(['mine', 'queue', 'done'])), q('outlet_id', uuid()), q('limit', int())], responses: { 200: json(obj({ data: arr(ref('TaskExpanded')), scope: str() })) } });
add('/tasks/{id}/transition', 'post', { tags: [T.staff], operationId: 'transitionTask', summary: 'Validated task transition (completed requires required steps; verified supervisor+)', parameters: [p('id')], requestBody: body(ref('TransitionRequest')), responses: { 200: json(ref('TransitionResult')) } });
add('/tasks/{id}/assign', 'post', { tags: [T.staff], operationId: 'assignTask', summary: 'Assign to a staff member (supervisor/manager)', parameters: [p('id')], requestBody: body(obj({ assignee_id: str(), reason: nullable(str()) }, ['assignee_id'])), responses: { 200: json(obj({ task: ref('Task') })) } });
add('/work-orders/{id}', 'get', { tags: [T.staff], operationId: 'getWorkOrder', summary: 'Work order with template, results, events and task', parameters: [p('id')], responses: { 200: json(ref('WorkOrderDetail')) } });
add('/work-orders/{id}/steps/{key}', 'post', { tags: [T.staff], operationId: 'recordStep', summary: 'Record a checklist step result (numeric min/max, photo requires attachment, supervisor_verify gated)', parameters: [p('id'), p('key', str())], requestBody: body(ref('StepRequest')), responses: { 200: json(ref('StepResponse')) } });
add('/work-orders/:id/checkin', 'post', { tags: [T.staff], operationId: 'checkInWorkOrder', summary: 'Confirm the vehicle is on site (required before assignment; runs auto-assignment when enabled)', parameters: [p('id')], requestBody: json(obj({ bay: nullable(str()) })), responses: { 201: json(obj({ work_order: ref('WorkOrder'), task: nullable(ref('Task')), already: bool() })), 200: json(obj({ work_order: ref('WorkOrder'), task: nullable(ref('Task')), already: bool() })), 409: json(ERR, 'not allowed in this state') } });
add('/work-orders/{id}/pickup/verify', 'post', { tags: [T.staff], operationId: 'verifyPickupOtp', summary: 'Staff confirm the collection OTP the customer presents → vehicle collected (409 invalid_otp with attempts_remaining; locked after 5 failures)', parameters: [p('id')], requestBody: body(obj({ otp: str({ pattern: '^\\d{5}$', example: '48213' }) }, ['otp'])), responses: { 200: json(obj({ work_order: ref('WorkOrder'), collected_at: dt(), collected: bool() })) } });
add('/work-orders/{id}/pickup/resend', 'post', { tags: [T.staff], operationId: 'resendPickupOtp', summary: 'Re-send the same collection OTP (push + WhatsApp pickup_otp template); rate-limited to once a minute per work order', parameters: [p('id')], responses: { 200: json(obj({ work_order: ref('WorkOrder'), notification: arr(ref('NotifyOutcome')), retry_after_seconds: int() })) } });
add('/sync/batch', 'post', { tags: [T.staff], operationId: 'syncBatch', summary: 'Replay the offline queue in order', requestBody: body(obj({ operations: arr(ref('SyncOperation')) }, ['operations'])), responses: { 200: json(obj({ results: arr(ref('SyncResult')), applied: int(), conflicts: int(), rejected: int() })) } });
add('/staff/ops-summary', 'get', { tags: [T.staff], operationId: 'getOpsSummary', summary: 'Supervisor ops summary', parameters: [q('outlet_id', uuid()), q('date', date())], responses: { 200: json(obj({ outlet_id: uuid(), date: date(), counts: obj({ in_progress: int(), queued: int(), blocked: int(), done: int() }), needs_attention: arr({ type: 'object', additionalProperties: true }), team_load: arr(obj({ staff_id: str(), name: str(), role: str(), availability: str(), capacity: int(), active_tasks: int() })) })) } });
add('/staff/me/availability', 'put', { tags: [T.staff], operationId: 'setMyAvailability', summary: "Set the signed-in staff member's availability", requestBody: json(obj({ status: enumOf(['available', 'busy', 'break', 'off']) }, ['status'])), responses: { 200: json(obj({ availability: obj({ profile_id: str(), status: str(), capacity: int(), updated_at: dt() }) })) } });
add('/staff/team', 'get', { tags: [T.staff], operationId: 'getTeam', summary: 'Outlet team with skills, availability and load', parameters: [q('outlet_id', uuid())], responses: { 200: json(obj({ data: arr(obj({ id: str(), full_name: str(), name: str({ description: 'Alias of full_name' }), role: str(), avatar_url: nullable(str()), is_primary: bool(), skills: arr(str()), availability: str(), capacity: int(), active_task_count: int(), active_tasks: int({ description: 'Alias of active_task_count' }) })) })) } });
add('/staff/customers', 'get', { tags: [T.staff], operationId: 'searchStaffCustomers', summary: 'Search customers by name, phone (any formatting), e-mail or plate (audited customer.search)', parameters: [q('search', str({ minLength: 2, maxLength: 80 }), true), q('limit', int({ minimum: 1, maximum: 25, default: 10 }))], responses: { 200: json(obj({ data: arr(ref('StaffCustomer')) })) } });
add('/staff/customers', 'post', { tags: [T.staff], operationId: 'createStaffCustomer', summary: 'Register a walk-in customer (walkin_<uuid> profile, claimed on sign-up by e-mail or phone); 409 with existing_customer when the phone/e-mail exists', requestBody: body(ref('StaffCustomerCreate')), responses: { 201: json(obj({ customer: ref('StaffCustomer') }), 'Created') } });
add('/staff/customers/{id}/vehicles', 'post', { tags: [T.staff], operationId: 'createStaffCustomerVehicle', summary: 'Add a vehicle for a customer (409 with existing_vehicle_id on duplicate plate/VIN unless force)', parameters: [p('id', str())], requestBody: body(ref('VehicleCreate')), responses: { 201: json(obj({ vehicle: ref('Vehicle'), duplicate: bool() }), 'Created'), 200: json(obj({ vehicle: ref('Vehicle'), duplicate: bool() }), 'Duplicate replay / forced merge') } });
add('/staff/leaderboard', 'get', { tags: [T.staff], operationId: 'getLeaderboard', summary: 'Points leaderboard and badges', parameters: [q('outlet_id', uuid()), q('period', enumOf(['week', 'month']))], responses: { 200: json(obj({ period: str(), period_start: dt(), rows: arr(ref('LeaderboardRow')), me: nullable(ref('LeaderboardRow')), badges: arr(obj({ badge: { type: 'object', additionalProperties: true }, earned_at: nullable(dt()) })) })) } });
add('/inventory', 'get', { tags: [T.inv], operationId: 'listInventory', summary: 'Items with open alert', parameters: [q('outlet_id', uuid())], responses: { 200: json(obj({ data: arr(ref('InventoryItem')), outlet_id: uuid() })) } });
add('/inventory/{id}/movements', 'post', { tags: [T.inv], operationId: 'recordMovement', summary: 'Record a movement (technician: usage/reorder_request; manager: any)', parameters: [p('id')], requestBody: body(ref('MovementRequest')), responses: { 201: json(ref('MovementResult'), 'Recorded'), 200: json(ref('MovementResult'), 'Replay') } });
add('/inventory/{id}', 'patch', { tags: [T.inv], operationId: 'updateInventoryItem', summary: 'Manager: threshold/name/unit (audited)', parameters: [p('id')], requestBody: body(obj({ reorder_threshold: num(), name: str(), unit: str() })), responses: { 200: json(obj({ item: ref('InventoryItem') })) } });

// Admin
add('/admin/kpis', 'get', { tags: [T.adm], operationId: 'getKpis', summary: 'Dashboard KPIs: period=today|week|month (calendar presets) or explicit from/to (default last 7 days)', parameters: [q('outlet_id', uuid()), q('period', enumOf(['today', 'week', 'month'])), q('from', dt()), q('to', dt())], responses: { 200: json(ref('Kpis')) } });
add('/admin/exceptions', 'get', { tags: [T.adm], operationId: 'getExceptions', summary: 'Blocked, overdue, stock and payment exceptions', parameters: [q('outlet_id', uuid())], responses: { 200: json(obj({ data: arr(ref('ExceptionItem')) })) } });
add('/admin/activity', 'get', { tags: [T.adm], operationId: 'getActivity', summary: 'Live activity feed', parameters: [q('outlet_id', uuid()), q('limit', int())], responses: { 200: json(obj({ data: arr(ref('ActivityItem')) })) } });
add('/admin/bookings', 'get', { tags: [T.adm], operationId: 'adminListBookings', summary: 'Live bookings table: Booking rows + work_order summary, latest payment, created_by_name; search matches ref, customer name or plate', parameters: [...pageParams, q('outlet_id', uuid()), q('date', date()), q('status', str({ description: 'Comma-separated statuses' })), q('search', str())], responses: { 200: json(paged({ allOf: [ref('Booking'), obj({ payment: nullable(obj({ id: uuid(), status: enumOf(paymentStatus), receipt_no: nullable(str()), amount_cents: int(), method: nullable(str()), provider: str(), verified_at: nullable(dt()) })), created_by_name: nullable(str()) })] })) } });
add('/admin/work-orders', 'get', { tags: [T.adm], operationId: 'adminListWorkOrders', summary: 'Work-order board: active work orders plus those finished since done_since (default start of today UTC), or exactly the given statuses', parameters: [q('outlet_id', uuid()), q('status', str({ description: 'Comma-separated statuses' })), q('done_since', dt()), q('limit', int({ minimum: 1, maximum: 500, default: 200 }))], responses: { 200: json(obj({ data: arr(ref('AdminWorkOrder')) })) } });
add('/admin/work-orders/{id}', 'get', { tags: [T.adm], operationId: 'adminGetWorkOrder', summary: 'One work order in the board shape (with task_events audit trail)', parameters: [p('id')], responses: { 200: json(obj({ work_order: ref('AdminWorkOrder') })) } });
add('/admin/outlets', 'get', { tags: [T.adm], operationId: 'adminListOutlets', summary: 'All outlets', responses: { 200: json(obj({ data: arr(ref('Outlet')) })) } });
add('/admin/outlets', 'post', { tags: [T.adm], operationId: 'adminCreateOutlet', summary: 'Create outlet (audited)', requestBody: body(ref('Outlet')), responses: { 201: json(obj({ outlet: ref('Outlet') }), 'Created') } });
add('/admin/outlets/{id}', 'patch', { tags: [T.adm], operationId: 'adminUpdateOutlet', summary: 'Update outlet (audited)', parameters: [p('id')], requestBody: body(ref('Outlet')), responses: { 200: json(obj({ outlet: ref('Outlet') })) } });
add('/admin/outlets/{id}', 'delete', { tags: [T.adm], operationId: 'adminDeactivateOutlet', summary: 'Deactivate outlet', parameters: [p('id')], responses: { 204: { description: 'Deactivated' } } });
add('/admin/services', 'get', { tags: [T.adm], operationId: 'adminListServices', summary: 'All services (incl. inactive) with their global composition', responses: { 200: json(obj({ data: arr(ref('AdminService')) })) } });
add('/admin/services', 'post', { tags: [T.adm], operationId: 'adminCreateService', summary: 'Create service (+ global components; audited). by_quote needs no prices, from/fixed need one; add-ons need addon_group_name; self/cyclic composition → 400', requestBody: body(ref('ServiceInput')), responses: { 201: json(obj({ service: ref('AdminService') }), 'Created') } });
add('/admin/services/{id}', 'put', { tags: [T.adm], operationId: 'adminUpdateService', summary: 'Update service; `components` replaces the global set atomically (audited service.update)', parameters: [p('id')], requestBody: body(ref('ServiceInput')), responses: { 200: json(obj({ service: ref('AdminService') })) } });
add('/admin/services/{id}', 'patch', { tags: [T.adm], operationId: 'adminPatchService', summary: 'Alias of PUT (partial update)', parameters: [p('id')], requestBody: body(ref('ServiceInput')), responses: { 200: json(obj({ service: ref('AdminService') })) } });
add('/admin/services/{id}', 'delete', { tags: [T.adm], operationId: 'adminDeactivateService', summary: 'Deactivate service', parameters: [p('id')], responses: { 204: { description: 'Deactivated' } } });
add('/admin/outlets/{id}/services', 'get', { tags: [T.adm], operationId: 'adminListOutletServices', summary: 'Outlet offers incl. unavailable, composition resolved (components_source: outlet|global|none)', parameters: [p('id')], responses: { 200: json(obj({ data: arr(ref('OutletServiceOffer')), groups: arr(enumOf(serviceGroups)) })) } });
add('/admin/outlet-services', 'get', { tags: [T.adm], operationId: 'adminOutletServiceMatrix', summary: 'Outlet × service matrix (all outlets, or one visible outlet)', parameters: [q('outlet_id', uuid())], responses: { 200: json(obj({ data: arr(ref('OutletService')) })) } });
add('/admin/outlets/{id}/services/{serviceId}', 'put', { tags: [T.adm], operationId: 'adminUpsertOutletService', summary: 'Upsert the outlet binding: wording, per-size prices, mode/VAT overrides, availability, outlet composition (`components: null` = global). Audited outlet_service.update', parameters: [p('id'), p('serviceId')], requestBody: body(ref('OutletServiceInput')), responses: { 200: json(obj({ outlet_service: ref('OutletServiceOffer') })) } });
add('/admin/outlets/{id}/services/{serviceId}', 'delete', { tags: [T.adm], operationId: 'adminDeleteOutletService', summary: 'Remove the outlet binding (and its outlet-specific composition rows)', parameters: [p('id'), p('serviceId')], responses: { 204: { description: 'Removed' } } });
add('/admin/users', 'get', { tags: [T.adm], operationId: 'adminListUsers', summary: 'Staff users', parameters: [...pageParams, q('role', str()), q('search', str()), q('outlet_id', uuid())], responses: { 200: json(paged({ allOf: [ref('Profile'), obj({ staff_outlets: arr(obj({ outlet_id: uuid(), is_primary: bool() })), staff_skills: arr(obj({ skill: str() })) })] })) } });
add('/admin/users', 'post', { tags: [T.adm], operationId: 'adminInviteUser', summary: 'Create Firebase user + profile + outlets; sets claims', requestBody: body(obj({ email: str({ format: 'email' }), full_name: str(), role: enumOf(roles), phone: nullable(str()), outlet_ids: arr(uuid()), skills: arr(str()), invite: enumOf(['password', 'link']) }, ['email', 'full_name', 'role'])), responses: { 201: json(obj({ profile: ref('Profile'), uid: str(), temporary_password: nullable(str()), invite_link: nullable(str()) }), 'Created') } });
add('/admin/users/{id}', 'patch', { tags: [T.adm], operationId: 'adminUpdateUser', summary: 'Role/outlets/skills/is_active (is_active=false revokes refresh tokens)', parameters: [p('id', str())], requestBody: body(obj({ role: enumOf(roles), outlet_ids: arr(uuid()), skills: arr(str()), is_active: bool(), full_name: str(), phone: nullable(str()) })), responses: { 200: json(obj({ profile: ref('Profile'), outlet_ids: arr(uuid()) })) } });
add('/admin/customers', 'get', { tags: [T.adm], operationId: 'adminSearchCustomers', summary: 'Search customers by name, e-mail, phone or plate (access logged); rows carry vehicle_count, booking_count and the loyalty + plan summary', parameters: [...pageParams, q('search', str())], responses: { 200: json(paged(ref('AdminCustomer'))) } });
add('/admin/customers/{id}', 'get', { tags: [T.adm], operationId: 'adminGetCustomer', summary: 'Customer 360 (access logged) incl. membership summary', parameters: [p('id', str())], responses: { 200: json(obj({ customer: ref('Profile'), vehicle_count: int(), booking_count: int(), loyalty: nullable(obj({ tier: enumOf(tiers), balance_points: int(), lifetime_points: int(), plan_code: nullable(str()), plan_name: nullable(str()), included_remaining: int() })), vehicles: arr(ref('Vehicle')), bookings: arr(ref('Booking')), loyalty_account: nullable(ref('LoyaltyAccount')), ledger: arr(ref('LedgerEntry')), payments: arr(ref('Payment')), membership: ref('MembershipSummary') })) } });
add('/admin/customers/{id}/membership', 'post', { tags: [T.adm], operationId: 'adminEnrolCustomerMembership', summary: 'Manager/admin: enrol a customer at the counter (same as the staff route; audited membership.enrol)', parameters: [p('id', str())], requestBody: body(ref('MembershipEnrol')), responses: { 201: json(ref('MembershipEnrolled'), 'Enrolled'), 200: json(ref('MembershipEnrolled'), 'Replay') } });
add('/admin/memberships/plans', 'get', { tags: [T.adm], operationId: 'adminListMembershipPlans', summary: 'Plans (incl. inactive) with member_count (active + past_due) and mrr_cents (active)', responses: { 200: json(obj({ data: arr(ref('AdminMembershipPlan')) })) } });
add('/admin/memberships/plans/{code}', 'put', { tags: [T.adm], operationId: 'adminUpdateMembershipPlan', summary: 'Manager/admin: update fee/discount/copy and replace groups + entitlements by code (ids kept when the code exists so usage rows stay valid; 409 when removing an entitlement that has usage; fee applies from the next invoice). Audited membership_plan.update', parameters: [p('code', str({ example: 'gold' }))], requestBody: body(ref('MembershipPlanInput')), responses: { 200: json(obj({ plan: ref('AdminMembershipPlan') })) } });
add('/admin/memberships', 'get', { tags: [T.adm], operationId: 'adminListMemberships', summary: 'Members (newest first) with plan, status, period, allowances used/remaining and open invoice', parameters: [...pageParams, q('status', str({ description: 'Comma-separated: pending|active|past_due|cancelled|expired' })), q('plan_code', str()), q('q', str({ description: 'Member name, phone, e-mail or membership ref' }))], responses: { 200: json(paged(ref('MemberRow'))) } });
add('/admin/memberships/run-renewals', 'post', { tags: [T.adm], operationId: 'adminRunMembershipRenewals', summary: 'Run the daily renewals job now (same logic as the membershipRenewals schedule; audited)', responses: { 200: json(ref('RenewalRun')) } });
add('/admin/memberships/{id}/cancel', 'post', { tags: [T.adm], operationId: 'adminCancelMembership', summary: 'Cancel a membership at period end or immediately (audited membership.cancel)', parameters: [p('id')], requestBody: body(obj({ at_period_end: { type: 'boolean', default: true }, reason: nullable(str()) }), false), responses: { 200: json(obj({ membership: ref('Membership') })) } });
add('/admin/memberships/{id}/invoices/{invoiceId}/record-payment', 'post', { tags: [T.adm], operationId: 'adminRecordMembershipInvoicePayment', summary: 'Record a counter payment for a pending membership invoice (rolls the period; audited)', parameters: [p('id'), p('invoiceId')], requestBody: body(ref('MembershipRecordPayment')), responses: { 201: json(ref('MembershipPaymentRecorded'), 'Recorded'), 200: json(ref('MembershipPaymentRecorded'), 'Replay') } });
add('/admin/loyalty/config', 'get', { tags: [T.adm], operationId: 'getLoyaltyConfig', summary: 'Published and draft loyalty config', responses: { 200: json(obj({ published: nullable(ref('LoyaltyConfig')), draft: nullable(ref('LoyaltyConfig')) })) } });
add('/admin/loyalty/config/draft', 'put', { tags: [T.adm], operationId: 'putLoyaltyDraft', summary: 'Create/update the draft', requestBody: body(obj({ tiers: arr(ref('LoyaltyTier')), rules: ref('LoyaltyRules'), change_note: str() }, ['tiers', 'rules'])), responses: { 200: json(obj({ draft: ref('LoyaltyConfig') })) } });
add('/admin/loyalty/config/publish', 'post', { tags: [T.adm], operationId: 'publishLoyaltyConfig', summary: 'Admin: draft → published (previous archived, audited)', responses: { 200: json(obj({ published: ref('LoyaltyConfig'), archived: nullable(obj({ id: uuid(), version: int() })) })) } });
add('/admin/loyalty/config/discard', 'post', { tags: [T.adm], operationId: 'discardLoyaltyDraft', summary: 'Discard the draft', responses: { 200: json(obj({ discarded: obj({ id: uuid(), version: int() }) })) } });
add('/admin/inventory', 'get', { tags: [T.adm], operationId: 'adminListInventory', summary: 'Inventory across outlets (outlet_name, capacity, blocking_work_orders, open alert)', parameters: [q('outlet_id', uuid()), q('alerts_first', enumOf(['true', 'false']))], responses: { 200: json(obj({ data: arr(ref('InventoryItem')) })) } });
add('/admin/staff/performance', 'get', { tags: [T.adm], operationId: 'getStaffPerformance', summary: 'Tasks completed, cycle time, compliance, points', parameters: [q('outlet_id', uuid()), q('period', enumOf(['today', 'week', 'month', 'quarter']))], responses: { 200: json(obj({ period: str(), from: dt(), to: dt(), data: arr(ref('StaffPerformanceRow')) })) } });
add('/admin/templates', 'get', { tags: [T.adm], operationId: 'listTemplates', summary: 'Checklist templates', responses: { 200: json(obj({ data: arr(ref('ChecklistTemplate')) })) } });
add('/admin/templates', 'post', { tags: [T.adm], operationId: 'createTemplate', summary: 'Create template v1', requestBody: body(obj({ name: str(), category: enumOf(['car_wash', 'auto_body']), steps: arr(ref('ChecklistStep')), outlet_id: nullable(uuid()), status: enumOf(['draft', 'published']) }, ['name', 'category', 'steps'])), responses: { 201: json(obj({ template: ref('ChecklistTemplate') }), 'Created') } });
add('/admin/templates/{id}', 'put', { tags: [T.adm], operationId: 'versionTemplate', summary: 'Publish a new version (previous archived; services re-pointed)', parameters: [p('id')], requestBody: body(obj({ name: str(), category: enumOf(['car_wash', 'auto_body']), steps: arr(ref('ChecklistStep')), outlet_id: nullable(uuid()), status: enumOf(['draft', 'published']), publish: { ...bool(), description: 'Shorthand for status: false → draft, true → published' } }, ['steps'])), responses: { 201: json(obj({ template: ref('ChecklistTemplate'), previous: obj({ id: uuid(), version: int() }) }), 'New version') } });
add('/admin/audit', 'get', { tags: [T.adm], operationId: 'listAudit', summary: 'Audit events (admin/finance: all; manager: own outlets) with actor_name', parameters: [...pageParams, q('entity_type', str()), q('entity_id', str()), q('actor_id', str()), q('action', str())], responses: { 200: json(paged(ref('AuditEvent'))) } });
add('/admin/exports/{report}', 'get', { tags: [T.adm], operationId: 'exportCsv', summary: 'CSV export with metadata header lines (generated_at, filters, scope)', parameters: [p('report', str({ enum: ['bookings.csv', 'payments.csv', 'inventory.csv', 'staff_performance.csv', 'loyalty.csv', 'memberships.csv'] })), q('outlet_id', uuid()), q('from', dateOrDt, false, 'YYYY-MM-DD (from 00:00Z) or ISO date-time; default 30 days ago'), q('to', dateOrDt, false, 'YYYY-MM-DD (to 23:59:59.999Z) or ISO date-time; default now')], responses: { 200: { description: 'CSV file', content: { 'text/csv': { schema: str() } } } } });
add('/admin/payments', 'get', { tags: [T.adm], operationId: 'adminListPayments', summary: 'Payments with booking ref, customer, method brand/last4 and receipt (finance-safe; same rows as payments.csv)', parameters: [q('outlet_id', uuid()), q('from', dateOrDt, false, 'YYYY-MM-DD or ISO date-time; default 30 days ago'), q('to', dateOrDt, false, 'YYYY-MM-DD or ISO date-time; default now'), q('status', str(), false, 'Comma-separated payment statuses'), q('limit', int({ minimum: 1, maximum: 200, default: 50 })), q('cursor', str())], responses: { 200: json({ allOf: [obj({ range: obj({ from: dt(), to: dt() }) }), paged(ref('AdminPayment'))] }) } });
add('/admin/reports/summary', 'get', { tags: [T.adm], operationId: 'getReportSummary', summary: 'Financial + operational summary computed from the same queries as the CSV exports (REP-005)', parameters: [q('outlet_id', uuid()), q('from', dateOrDt, false, 'YYYY-MM-DD or ISO date-time; default 30 days ago'), q('to', dateOrDt, false, 'YYYY-MM-DD or ISO date-time; default now')], responses: { 200: json(ref('ReportSummary')) } });
add('/admin/integrations', 'get', { tags: [T.adm], operationId: 'getIntegrations', summary: 'Integration status cards: Supabase probe, Firebase project, payments provider, WhatsApp', responses: { 200: json(obj({ data: arr(ref('IntegrationCard')) })) } });
add('/admin/notifications', 'get', { tags: [T.adm], operationId: 'adminListNotifications', summary: 'Delivery log across channels (provider status, error codes, receipts)', parameters: [...pageParams, q('status', str({ description: 'Comma-separated: queued|sent|delivered|failed|suppressed' })), q('channel', str({ description: 'Comma-separated: push|whatsapp|sms|email' })), q('recipient_id', str()), q('template_key', str())], responses: { 200: json(paged(ref('AdminNotification'))) } });
add('/admin/notifications/{id}/resend', 'post', { tags: [T.adm], operationId: 'adminResendNotification', summary: 'Re-send a failed/suppressed push or WhatsApp notification from its stored template + payload.vars (bumps attempts; audited)', parameters: [p('id')], responses: { 200: json(obj({ notification: ref('NotificationFull'), outcome: ref('NotifyOutcome') })) } });
add('/admin/flags', 'get', { tags: [T.adm], operationId: 'listFlags', summary: 'Feature flags', responses: { 200: json(obj({ data: arr(ref('FeatureFlag')), effective: { type: 'object', additionalProperties: bool() } })) } });
add('/admin/flags/{key}', 'patch', { tags: [T.adm], operationId: 'updateFlag', summary: 'Toggle a flag (audited)', parameters: [p('key', str())], requestBody: body(obj({ enabled: bool(), description: str() }, ['enabled'])), responses: { 200: json(obj({ flag: ref('FeatureFlag') })) } });

// Notifications
add('/notifications', 'get', { tags: [T.not], operationId: 'listNotifications', summary: 'Own notifications', parameters: pageParams, responses: { 200: json(paged(ref('Notification'))) } });
add('/notifications/{id}/read', 'post', { tags: [T.not], operationId: 'markNotificationRead', summary: 'Mark as read', parameters: [p('id')], responses: { 200: json(obj({ notification: obj({ id: uuid(), read_at: dt() }) })) } });
add('/notifications/twilio/status', 'post', { tags: [T.not], operationId: 'twilioStatusCallback', summary: 'Twilio delivery-status callback (form-encoded; X-Twilio-Signature validated against PUBLIC_API_BASE_URL/v1/notifications/twilio/status; idempotent by MessageSid)', security: [], parameters: [{ name: 'X-Twilio-Signature', in: 'header', required: true, schema: str() }], requestBody: { required: true, content: { 'application/x-www-form-urlencoded': { schema: ref('TwilioStatusCallback') } } }, responses: { 200: json(obj({ ignored: bool(), reason: str(), notification_id: uuid(), status: enumOf(['queued', 'sent', 'delivered', 'failed', 'suppressed']), provider_status: str() })) } });

const spec = {
  openapi: '3.0.3',
  info: {
    title: 'Sparkling REST API',
    version: '1.0.0',
    description: 'Sparkling platform backend (SRS v1.0). All JSON, snake_case, ISO-8601 UTC timestamps, money in integer ZAR cents. Mutating routes accept `Idempotency-Key` (or `client_op_id` in the body); replays return the cached first response. Every response carries `X-Correlation-Id`. Clients send `X-Client-App` and `X-Client-Version`.',
    contact: { name: 'Sparkling engineering', email: 'dev@sparkling.co.za' },
    license: { name: 'Proprietary', url: 'https://sparkling.co.za/legal' },
  },
  servers: [
    { url: 'https://europe-west1-sparkling-4e89d.cloudfunctions.net/api/v1', description: 'dev (Cloud Functions 2nd gen)' },
    { url: 'http://127.0.0.1:5001/sparkling-4e89d/europe-west1/api/v1', description: 'Firebase emulator' },
  ],
  tags: Object.values(T).map((name) => ({ name, description: `${name} endpoints` })),
  security: [{ bearerAuth: [] }],
  paths,
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'Firebase ID token' } },
    parameters: {},
    responses: {
      ValidationError: errResp('validation_error (400)'),
      Unauthenticated: errResp('unauthenticated (401)'),
      Forbidden: errResp('forbidden (403)'),
      NotFound: errResp('not_found (404)'),
      Conflict: errResp('conflict / invalid_transition (409)'),
      Gone: errResp('gone (410) — expired quote link or quotation past valid_until'),
      RateLimited: errResp('rate_limited (429)'),
      Internal: errResp('internal (500) — never includes stack traces'),
    },
    schemas,
  },
};
delete spec.components.parameters;
fs.writeFileSync(require('node:path').join(__dirname, '..', 'openapi.yaml'), '# Generated by scripts/gen-openapi.cjs — edit that file, then `node scripts/gen-openapi.cjs`.\n' + yaml.dump(spec, { noRefs: true, lineWidth: 200 }));
console.log(`wrote openapi.yaml with ${Object.keys(paths).length} paths`);
