#!/usr/bin/env node
// Generates the shared country / dial-code list for the phone inputs from libphonenumber-js
// metadata (+ Intl region names). Run from apps/admin (where libphonenumber-js is installed):
//   node ../../tools/phone/gen_countries.mjs
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';

const require = createRequire(import.meta.url);
const { getCountries, getCountryCallingCode } = require(resolve(process.cwd(), 'node_modules/libphonenumber-js/min'));
const names = new Intl.DisplayNames(['en'], { type: 'region' });
const flag = (iso) => String.fromCodePoint(...[...iso].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));

const rows = getCountries()
  .map((iso) => ({ iso, dial: String(getCountryCallingCode(iso)), name: names.of(iso) ?? iso, flag: flag(iso) }))
  .filter((r) => r.name && r.name !== r.iso)
  .sort((a, b) => a.name.localeCompare(b.name));

const root = resolve(process.cwd(), '../..');
const header = '// GENERATED by tools/phone/gen_countries.mjs — do not edit by hand.\n';

writeFileSync(
  resolve(root, 'apps/admin/src/lib/countries.ts'),
  header +
    `export interface Country { iso: string; dial: string; name: string; flag: string }\n` +
    `export const DEFAULT_COUNTRY = 'ZA';\n` +
    `export const COUNTRIES: readonly Country[] = [\n` +
    rows.map((r) => `  { iso: '${r.iso}', dial: '${r.dial}', name: ${JSON.stringify(r.name)}, flag: '${r.flag}' },`).join('\n') +
    `\n];\n`,
);

writeFileSync(
  resolve(root, 'packages/sparkling_core/lib/src/models/countries.dart'),
  header +
    `/// Country for the phone-number picker (ISO 3166-1 alpha-2, dial code, name, flag).\n` +
    `class Country {\n  const Country(this.iso, this.dial, this.name, this.flag);\n  final String iso;\n  final String dial;\n  final String name;\n  final String flag;\n\n` +
    `  @override\n  String toString() => '$flag +$dial $name';\n}\n\n` +
    `const String defaultCountryIso = 'ZA';\n\n` +
    `const List<Country> countries = [\n` +
    rows.map((r) => `  Country('${r.iso}', '${r.dial}', ${JSON.stringify(r.name).replace(/\$/g, '\\$')}, '${r.flag}'),`).join('\n') +
    `\n];\n`,
);
console.log(`wrote ${rows.length} countries`);
